pentaho/pentaho-reporting

engine/extensions-pentaho-metadata/test/org/pentaho/reporting/engine/classic/extensions/datasources/pmd/PentahoMetaDataTest.java
=> BACKLOG-1764 - cleanup test case.after developer change.

designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/AbstractSaveReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/CloseReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/SaveReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/SaveReportAsAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/migration/MigrationDialog.java
=> [PRD-5286] fixed the issue and refactored the saving actions

designer/report-designer-extension-pentaho/source/org/pentaho/reporting/designer/extensions/pentaho/repository/actions/PublishToServerAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/AbstractSaveReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/CloseReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/SaveReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/SaveReportAsAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/migration/MigrationDialog.java
Picked from #556 and 45b2452 
@tmorgner
=> [SP-1614] backport of PRD-5286 - Wrong report title after publishing from PRD

engine/extensions-cda/source/org/pentaho/reporting/engine/classic/extensions/datasources/cda/CdaDataFactoryCore.java, engine/extensions-cda/source/org/pentaho/reporting/engine/classic/extensions/datasources/cda/meta-datafactory.xml
Fixes: http://jira.pentaho.com/browse/PRD-5414
=> Added query hash and referenced fields support to CDA queries to enable data/metadata caching

build-res/multibuild-shared.xml, engine/tools/build.properties
Added javadoc.packagenames property for dist-javadoc target
@smaring @lgrill-pentaho
=> [ENGOPS-640] Added javadoc package path

libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/PublishRestUtil.java
Merged with this PR:
https://github.com/pentaho/pentaho-platform/pull/2287
=> BISERVER-12457 - REGRESSION: User with 'Administer Security' permission can publish reports

libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/PublishRestUtil.java
Merged with this PR:
https://github.com/pentaho/pentaho-platform/pull/2283
=> SP-1747 - Regression of BISERVER-12457 - User with Administer Security permission can publish reports (5.3 Suite)

designer/report-designer-assembly/build.properties, designer/report-designer-assembly/ivy.xml
Add spark plugin
https://github.com/pentaho/pentaho-kettle/pull/1230
@mdamour1976 @tmorgner
=> [BAD-170] Support for Spark

engine/extensions-drilldown/source/org/pentaho/reporting/engine/classic/extensions/drilldown/messages_de.properties
What was done:
1) added updated files
=> BACKLOG-3306 - Checkin 5.4 Localization files from Acclaro (2nd drop)

libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/JCRSolutionDirectFileModel.java
=> [PRD-5466] - Fixed Libspensol JCRSolutionDirectFileModel.getData issue

engine/core/source/org/pentaho/reporting/engine/classic/core/AttributeNames.java
Backport of: https://github.com/pentaho/pentaho-reporting/pull/625
@rfellows 
Please review.
=> SP-1901 - Backport of PIR-1142 - PIR: Adding two fields to groups the font of the second one is the same color as the background (5.4 Suite)

libraries/libformula/ivy.xml, libraries/libformula/source/org/pentaho/reporting/libraries/formula/function/information/IsNumberFunction.java, libraries/libformula/test/org/pentaho/reporting/libraries/formula/function/information/IsNumberFunctionTest.java
@tmorgner @mkambol @mdamour1976 please review and merge
=> [PDI-11377] fixed the IsNumber function issue

libraries/libformula/ivy.xml, libraries/libformula/source/org/pentaho/reporting/libraries/formula/function/information/IsNumberFunction.java, libraries/libformula/test/org/pentaho/reporting/libraries/formula/function/information/IsNumberFunctionTest.java
@tmorgner @mkambol @mdamour1976 please review and merge
=> [SP-1981] fixed the IsNumber function issue

designer/report-designer/src/org/pentaho/reporting/designer/core/model/data/AsynchronousDataSchemaManager.java
- recreate the actor if it was stopped (cherry picked from commit 3c05c24)
- apply Pentaho formatting to the whole class
@tmorgner, review it please. This is an adapted forwardport of  https://github.com/pentaho/pentaho-reporting/pull/644
=> [PRD-5363] - Sub-report: AskTimeOutException appears when user opening a sub-report.

libraries/libpensol/ivy.xml, libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModel.java, libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/RepositoryFileTreeDtoProxy.java, libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/libpensol.properties, libraries/libpensol/test/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModelTest.java, libraries/libpensol/test/org/pentaho/reporting/libraries/pensol/RepositoryFileTreeDtoProxyTest.java
- introduce a partial loading routine
- turn it on by default
- add tests
- apply proper formatting
@tmorgner, review it please.
/CCing @dkincade, @mbatchelor, @pentaho-nbaker, @pamval as all of you were involved in the discussion
=> [PRD-5300] - Publish dialog times out when publishing report to a Server with many home directories

designer/report-designer-extension-pentaho/ivy.xml, engine/extensions-kettle/ivy.xml, engine/extensions-mondrian/ivy.xml, libraries/libpensol/ivy.xml
!! Do not merge until we get the official go-ahead for VFS2.1.
=> [BACKLOG-4922]  Upgrading to vfs2.1

engine/core/ivy.xml, engine/extensions-kettle/ivy.xml, libraries/libbase/ivy.xml, libraries/libpensol/ivy.xml
Updated the poi dependency and required 3rd party dependencies.
@pentaho-nbaker @mbatchelor Let's discuss this before including ...
NOTE: there are other pull requests that all must go together
=> [PRD-5459] - Upgraded POI and associated 3rd party libraries

libraries/libformula/source/org/pentaho/reporting/libraries/formula/function/datetime/DateValueFunction.java, libraries/libformula/test/org/pentaho/reporting/libraries/formula/function/datetime/TimeValueFunctionTest.java
Patch contributed by: Lionel Elie Mamane - Thanks!
=> [PRD-5498] - TIMEVALUE() of a DateTime value always returns 0

designer/report-designer-assembly/build.assembly.sequential.xml
=> [BACKLOG-5204] Increase memory for Report Designer app

engine/extensions-cda/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/cda/Prd3828Test.java
- make Prd3828Test stable (eliminate dependency on hash map iteration order and environment's time zone)
@tmorgner, review it please.
This fixed the failed test, which was relying on HM's order and parsed timestamps in local time zone
=> [BACKLOG-5473] - Rename tests' folders in pentaho-reporting to "test-src"

engine/extensions-kettle/ivy.xml, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/BigDataKettleFactoryTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/FormulaArgumentTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/FormulaParameterTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/Prd5056Test.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/TableProducerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/parser/ArgumentReadHandlerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/parser/KettleDataSourceXmlFactoryModuleTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/parser/KettleTransFromRepositoryReadHandlerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/parser/VariableReadHandlerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/writer/EmdeddedTransformationProducerWriteHandlerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/writer/FileTransformationProducerWriteHandlerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/writer/KettleDataFactoryWriteHandlerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/writer/RepositoryTransformationProducerWriteHandlerTest.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/writer/TransformationProducerWriteHandlerLibTest.java
=> [BACKLOG-5409] - tests for pentaho-reporting-engine-classic-extensions-kettle

designer/datasource-editor-jdbc/ivy.xml, designer/datasource-editor-jdbc/source/org/pentaho/reporting/ui/datasources/jdbc/SimpleJdbcDataSourcePlugin.java, designer/datasource-editor-jdbc/source/org/pentaho/reporting/ui/datasources/jdbc/connection/JdbcConnectionDefinitionManager.java, designer/datasource-editor-jdbc/test-src/org/pentaho/reporting/ui/datasources/jdbc/SimpleJdbcDataSourcePluginTest.java, designer/datasource-editor-jdbc/test-src/org/pentaho/reporting/ui/datasources/jdbc/connection/DriverConnectionDefinitionTest.java, designer/datasource-editor-jdbc/test-src/org/pentaho/reporting/ui/datasources/jdbc/connection/JdbcConnectionDefinitionManagerTest.java, designer/datasource-editor-jdbc/test-src/org/pentaho/reporting/ui/datasources/jdbc/connection/JndiConnectionDefinitionTest.java
@tmorgner , @mdamour1976  please review.
I added a few tests for this module, however it has some UI stuff. This fact has negative effect on code coverage, but I think it would be cheaper to ignore it.
=> [BACKLOG-5408] - tests for pentaho-reporting-engine-datasource-editor-jdbc

libraries/libformula/test-src/org/pentaho/reporting/libraries/formula/function/userdefined/CsvArrayFunctionTest.java
- move CsvArrayFunctionTest to the proper folder
- uncomment the third test case
@tmorgner, review it please.
=> [PRD-5561] - Libformula Copy/Paste bug in CsvArrayFunction

libraries/libformula/test/org/pentaho/reporting/libraries/formula/function/userdefined/CsvArrayFunctionTest.java
- backport 3b7cc7ddf68bff66a1a215c7ed3b8ea80d67a633
@tmorgner, review it please. This is a backport of https://github.com/pentaho/pentaho-reporting/pull/697
=> [SP-2218] - Backport of PRD-5561 - Libformula Copy/Paste bug in CsvArrayFunction (6.0 Suite)

engine/testcases/test-src/org/pentaho/reporting/engine/classic/testcases/FullAttributeMetaDataValidationTest.java
=> [TEST] fixed the reason of compiling error - renamed package

engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/TextFieldParameterComponentTest.java, engine/extensions-mondrian/extensions-mondrian.iml, engine/extensions-pentaho-metadata/extensions-pentaho-metadata.iml, engine/extensions-toc/extensions-toc.iml, engine/legacy-charts/legacy-charts.iml, engine/testcases/testcases.iml, engine/wizard-core/wizard-core.iml, libraries/libbase/libbase.iml, libraries/libcss/libcss.iml, libraries/libdocbundle/libdocbundle.iml, libraries/libfonts/libfonts.iml, libraries/libformat/libformat.iml, libraries/libformula-ui/libformula-ui.iml, libraries/libformula/libformula.iml, libraries/libloader/libloader.iml, libraries/libpensol/libpensol.iml, libraries/librepository/librepository.iml, libraries/libsparkline/libsparkline.iml, libraries/libswing/libswing.iml, libraries/libxml/libxml.iml
and IntelliJ desperately wants to update the module files with a new linebreak
=> [PRD-5580] - Test fix Again!

engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/CategoricalChartExpression.java, engine/legacy-charts/test/org/pentaho/plugin/jfreereport/reportcharts/CategoricalChartExpressionTest.java
Backport of https://github.com/pentaho/pentaho-reporting/pull/715
@tmorgner @pamval 
Please review.
=> SP-2350 - Backport of PRD-4946 - Alignment issues with x-axis-ticks and x-axis-labels in Bar Charts (5.4 Suite)

engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/CategoricalChartExpression.java, engine/legacy-charts/test/org/pentaho/plugin/jfreereport/reportcharts/CategoricalChartExpressionTest.java
Cherry-pick of https://github.com/pentaho/pentaho-reporting/pull/715
@tmorgner @pamval 
Please review.
=> SP-2349 - Backport of PRD-4946 - Alignment issues with x-axis-ticks and x-axis-labels in Bar Charts (6.0 Suite)

designer/report-designer-assembly/resource/system/osgi/log4j.xml
- [PDI-14540] applied same solution that was applied to Spoon
- new  /system/osgi directory structure does *not* conflict with existing karaf build resource ( /system/karaf )
=> [BACKLOG-5967] PRD Warning message log4j.xml file not exist

engine/core/source/org/pentaho/reporting/engine/classic/core/layout/output/crosstab/CrosstabOutputHelper.java, engine/core/source/org/pentaho/reporting/engine/classic/core/layout/process/PaginationStep.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/bugs/Prd5573IT.java
Prevent infinite loop with error when table 
header is higher than allowed page height.
=> PRD-5573 Validate space reserved for "table-header'

designer/report-designer/src/org/pentaho/reporting/designer/core/editor/ContextMenuUtility.java, designer/report-designer/test-src/org/pentaho/reporting/designer/core/editor/ContextMenuUtilityTest.java
Checking if query name is used more than one time and disabling activation context menu item for such queries.
=> PRD-5562 disable "Activate query" for query with duplicated name

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/ButtonParameterComponent.java
Allow JList to handle scrollbars.
=> PRD-5370 - fix horizontal scroll for multiple select button

engine/core/source/org/pentaho/reporting/engine/classic/core/style/ElementStyleSheet.java, engine/core/source/org/pentaho/reporting/engine/classic/core/style/StyleKey.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/style/ElementStyleSheetTest.java
- make some clean-up:
- replace TODOs with comments
- fix Checkstyle violations
@tmorgner, review it please. This is a cosmetic fix -- just comments and Checkstyle
=> [PRD-5625] - Improve memory usage by packing byte array in styles

designer/report-designer/src/org/pentaho/reporting/designer/core/editor/ContextMenuUtility.java, designer/report-designer/test-src/org/pentaho/reporting/designer/core/editor/ContextMenuUtilityTest.java
- backport commits bbdfd0e & f7cb2f4
@tmorgner, review it please. This is a backport of https://github.com/pentaho/pentaho-reporting/pull/722
=> [SP-2504] - Backport of PRD-5562 - it is impossible to change the type of source to another if they each have a query with the same name. (6.0 Suite)

engine/core/source/org/pentaho/reporting/engine/classic/core/AttributeNames.java, engine/core/source/org/pentaho/reporting/engine/classic/core/MasterReport.java, engine/core/source/org/pentaho/reporting/engine/classic/core/metadata/messages.properties, engine/core/source/org/pentaho/reporting/engine/classic/core/metadata/meta-elements.xml
PR was merged to master - it is not a proper flow and my fault.
These changes don't affect functionality because we simply add new properties here, so we can keep them safely.
=> Sync with master

designer/report-designer/src/org/pentaho/reporting/designer/core/editor/drilldown/DrillDownEditor.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/drilldown/DrillDownParameterTableModel.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/drilldown/Messages.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/drilldown/messages.properties, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/drilldown/swing/SwingSelfDrillDownUi.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/drilldown/swing/SwingSelfDrillDownUiProfile.java, designer/report-designer/src/org/pentaho/reporting/designer/core/report-designer.properties
- Swing version of the self-drilldown.xul dialog.
=> [PRD-4160] Xul based DrillDown dialogs in Report Designer cannot be internationalized

designer/report-designer/src/org/pentaho/reporting/designer/core/report-designer.properties
=> [BACKLOG-6227] Update Help URL for all products.

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/fast/csv/FastCsvReportUtil.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/fast/xls/FastExcelReportUtil.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/csv/CSVReportUtil.java
We need them to set listeners.
@tmorgner
=> [PRD-5599] Utility methods with listener parameter

designer/report-designer-assembly/build.properties, designer/report-designer-assembly/ivy.xml
=> Add missing karaf dependency props

engine/core/source/org/pentaho/reporting/engine/classic/core/event/ReportProgressEvent.java, engine/core/source/org/pentaho/reporting/engine/classic/core/layout/output/AbstractReportProcessor.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/event/ReportProgressEventTest.java
Added test and changed logic, now it works as expected.
Thomas, please review.
@tmorgner
=> [BACKLOG-7159] Add total pages field to report progress event

libraries/librepository/source/org/pentaho/reporting/libraries/repository/stream/WrappedInputStream.java, libraries/librepository/source/org/pentaho/reporting/libraries/repository/stream/WrappedOutputStream.java, libraries/librepository/test-src/org/pentaho/reporting/libraries/repository/stream/WrappedInputStreamTest.java, libraries/librepository/test-src/org/pentaho/reporting/libraries/repository/stream/WrappedOutputStreamTest.java
=> [BACKLOG-7993] - Don't close streams received from outside

libraries/libformula/source/org/pentaho/reporting/libraries/formula/function/datetime/MinuteFunction.java, libraries/libformula/source/org/pentaho/reporting/libraries/formula/util/NumberUtil.java, libraries/libformula/test-src/org/pentaho/reporting/libraries/formula/function/datetime/MinuteFunctionTest.java, libraries/libformula/test-src/org/pentaho/reporting/libraries/formula/util/NumberUtilTest.java
Added new function for minute rounding.
Added appropriate tests.
@tmorgner, @mkambol, @hudak could you please review?
=> [PRD-5734] Open Formula timevalue returning bad data

libraries/libformula/test-src/org/pentaho/reporting/libraries/formula/function/datetime/MinuteFunctionTest.java
Just corrected comment place.
@tmorgner could you please review?
=> [PRD-5734][Makeup] Corrected comment place

engine/core/source/org/pentaho/reporting/engine/classic/core/function/StateSequence.java, engine/core/source/org/pentaho/reporting/engine/classic/core/function/TotalGroupSumFunction.java, engine/core/source/org/pentaho/reporting/engine/classic/core/function/TotalItemCountFunction.java, engine/core/source/org/pentaho/reporting/engine/classic/core/function/TotalItemMaxFunction.java, engine/core/source/org/pentaho/reporting/engine/classic/core/function/TotalItemMinFunction.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/parser/ext/factory/base/ClassFactoryImplTest.java
Finishing @prakapenka work.
Junits are on the way - need to see wingman's opinion.
@tmorgner
=> [BACKLOG-7998] - Improve perfomance of 'Total' functions

engine/core/ivy.xml
security vulnerability CVE-2015-3253 for groovy before 2.4.4
=> [PPP-3536] - Updated groovy to version 2.4.7 due to CVE-2015-3253

engine/extensions-kettle/ivy.xml
=> [BACKLOG-9099] - Add meta-inject plugin dependency

designer/report-designer-extension-pentaho/source/org/pentaho/reporting/designer/extensions/pentaho/repository/dialogs/RepositoryPublishDialog.java, designer/report-designer-extension-pentaho/source/org/pentaho/reporting/designer/extensions/pentaho/repository/messages.properties
Allow user to select Email output from the publish dialog
=> [BACKLOG-9531] - Add email output to the publish dialog

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/base/AbstractTableOutputProcessor.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/html/config-description.xml, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/html/configuration.properties, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/HtmlOutputProcessorMetaData.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/HtmlTextExtractorHelper.java
=> [BACKLOG-10064] - Configuration for rotated text as images

designer/report-designer-assembly/resource/samples/metadata.xmi, engine/extensions-pentaho-metadata/devresource/metadata/metadata.xmi, engine/extensions-pentaho-metadata/devresource/metadata/metadata2.xmi
- Role names in metadata.xmi were changed from Admin to Administrator
=> [BISERVER-12951] Aggregators and group by are not applied to fields on PRD report that uses metadata datasource is running on server

engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/AbstractElementType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/DateFieldType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/MessageType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/NumberFieldType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/RotatableText.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/TextFieldType.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/RotationTest.java
=> [BACKLOG-10072] - Some fields become null after rotation

engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/DateFieldType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/LabelType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/MessageType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/NumberFieldType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/ResourceFieldType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/ResourceLabelType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/ResourceMessageType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/RotatableText.java, engine/core/source/org/pentaho/reporting/engine/classic/core/filter/types/TextFieldType.java, engine/core/source/org/pentaho/reporting/engine/classic/core/layout/output/OutputProcessorFeature.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/pageable/plaintext/TextOutputProcessorMetaData.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/csv/helper/CSVOutputProcessorMetaData.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/RotationTest.java
=> [BACKLOG-10061] - Ignore rotation for CSV and TXT outputs

designer/report-designer-assembly/ivy.xml
http://jira.pentaho.com/browse/BACKLOG-10143
pentaho/big-data-plugin#715
=> [BACKLOG-10143]Remove pdi-spark-plugin

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactory.java
exceeded" error in Oracle DB
- added use CachedRowSet. It let doesn't keep open ResultSet for each
statement
- fix copyright comments
=> [PRD-5637]-Running PRPT on PRD throws "ORA-01000: maximum open cursors

engine/core/source/org/pentaho/reporting/engine/classic/core/Element.java
- fixed: add verification for expression
=> [PRD-5785]-Morphing Resource Labels clearing out SubReport

designer/report-designer-assembly/resource/resources/log4j.xml
work out of the box to identify what user is impersonating within the
cluster.
=> [BACKLOG-11172] As an administrator, I need the impersonation logging to

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtility.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtilityTest.java
=> [PRD-5746] Border radius values are saved under an incorrect key

engine/core/source/org/pentaho/reporting/engine/classic/core/cache/CachableTableModel.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/cache/CachableTableModelTest.java
=> [PRD-5757]-Results sets with booleans are not cached

engine/core/source/libformula.properties, engine/core/source/org/pentaho/reporting/engine/classic/core/function/formula/ResourceLookupFunction.java, engine/core/source/org/pentaho/reporting/engine/classic/core/function/formula/ResourceLookupFunction.properties, engine/core/source/org/pentaho/reporting/engine/classic/core/function/formula/ResourceLookupFunctionDescription.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/base/ParameterReportControllerPane.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/DatePickerParameterComponent.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/TextAreaParameterComponent.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/TextFieldParameterComponent.java, engine/core/source/org/pentaho/reporting/engine/classic/core/parameters/ParameterAttributeNames.java, engine/core/source/org/pentaho/reporting/engine/classic/core/parameters/ParameterDefinitionEntry.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/bugs/Prd3174IT.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/function/formula/ResourceLookupFunctionTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/gui/base/ParameterReportControllerPaneTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/DatePickerParameterComponentTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/TextAreaParameterComponentTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/TextFieldParameterComponentTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/parameters/DefaultReportParameterValidatorTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/parameters/ParameterDefinitionEntryTest.java
Introduce new formula for resource lookup. We may consider to review ResourceLookupFunction.properties  for better display values.
=> [backlog-10392] - parameter localizations engine/core

designer/report-designer/src/org/pentaho/reporting/designer/core/editor/parameters/ParameterDialog.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/parameters/messages/messages.properties
ParameterDialog class has massive check-style violations. To have a chance not to mess up with functionality with check-style changes I made check-style changes as separate commit.
So [CLEAN-UP] commit is for birds, [BACKLOG-XXX] is for people.
=> [BACKLOG-10736] - add UI translations Id input text field

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/DataDefinitionFileWriter.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/DataDefinitionFileWriterTest.java
=> [PRD-5766] Typo on code reads attribute as timout instead of timeout

engine/extensions/source/org/pentaho/reporting/engine/classic/extensions/modules/connections/PooledDatasourceHelper.java, engine/extensions/test-src/org/pentaho/reporting/engine/classic/extensions/modules/connections/PooledDatasourceHelperIT.java
PooledDatasourceHelper.convert() in reporting had the same
issue as the comparable method in platform.  Since this one
is unused I'm removing it.
=> [BACKLOG-11444] Pooled big-data connections fail

designer/report-designer-assembly/resource/resources/report-designer.properties, engine/core/source/org/pentaho/reporting/engine/classic/core/classic-engine.properties, engine/extensions-xpath/source/org/pentaho/reporting/engine/classic/extensions/datasources/xpath/LegacyXPathTableModel.java
[PPP-3584] PRD - Security Vulnerability when using XML file as datasource
- disable default support DTD in pentaho report designer
- add property for enable/disable support DTD
=> [PPP-3584] PRD - Security Vulnerability when using XML file as datasource

designer/report-designer-assembly/resource/resources/report-designer.properties, engine/core/source/org/pentaho/reporting/engine/classic/core/classic-engine.properties, engine/extensions-xpath/source/org/pentaho/reporting/engine/classic/extensions/datasources/xpath/LegacyXPathTableModel.java
Reverts pentaho/pentaho-reporting#845
=> Revert "[PPP-3584] PRD - Security Vulnerability when using XML file as datasource"

designer/report-designer/src/org/pentaho/reporting/designer/core/splash/SplashScreen.java
- switching splash screen text from black to white ( as new 7.0 splash screen image has a dark blue background )
=> [BACKLOG-11620] Update product App icons and splash screens

designer/report-designer/src/org/pentaho/reporting/designer/core/report-designer.properties
@pentaho/millenniumfalcon @pamval please review.
=> [BACKLOG-11781] PRD - link for documentation not updated (points to 6.1)

engine/core/source/org/pentaho/reporting/engine/classic/core/cache/CachableTableModel.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/cache/CachableTableModelTest.java
=> [SP-2955][PRD-5757]-Results sets with booleans are not cached

designer/report-designer-assembly/ivy.xml
@dkincade @kcruzada @pamval 7.0-SNAPSHOT looked good. Please review
CC: @CodeOnCoffee @mbatchelor @rmansoor @pentaho/rogueone 
Related PRs:
https://github.com/pentaho/pentaho-platform/pull/3216
https://github.com/pentaho/pentaho-kettle/pull/3105
https://github.com/pentaho/pentaho-reporting/pull/873
https://github.com/pentaho/pentaho-reportdesigner-ee/pull/55
=> [BACKLOG-11621] Removes JTDS driver dependency

designer/report-designer/ivy.xml, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/parameters/ParameterDialog.java, designer/report-designer/test-src/org/pentaho/reporting/designer/core/editor/parameters/ParameterDialogTest.java
backport from https://github.com/pentaho/pentaho-reporting/pull/863/commits
=> [BACKLOG-11906] - fix formula computation for empty label and data format

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/DataDefinitionFileWriter.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/DataDefinitionFileWriterTest.java
=> [SP-2963] Backport of PRD-5766 - Typo on code reads attribute as timout instead of timeout (6.1 Suite)

engine/extensions-kettle/extensions-kettle.eml, engine/extensions-kettle/ivy.xml, engine/extensions-pentaho-metadata/extensions-pentaho-metadata.eml
Reverts pentaho/pentaho-reporting#883
Reverting for now since the platform upgrade still needs work
=> Revert "[PPP-3570] - Use of vulnerable component Apache Axis2 v.1.5.2 - CVE-2…"

engine/extensions-kettle/extensions-kettle.eml, engine/extensions-kettle/ivy.xml, engine/extensions-pentaho-metadata/extensions-pentaho-metadata.eml
=> [PPP-3570] - revert

designer/datasource-editor-pmd/source/org/pentaho/reporting/ui/datasources/pmd/PmdDataSourceEditor.java, engine/extensions-kettle/source/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/DocumentHelper.java, engine/extensions-mondrian/source/org/pentaho/reporting/engine/classic/extensions/datasources/mondrian/MondrianUtil.java, libraries/configuration-editor/source/org/pentaho/reporting/tools/configeditor/util/DOMUtilities.java, libraries/libbase/source/org/pentaho/reporting/libraries/base/config/metadata/ConfigurationMetaDataParser.java, libraries/libbase/source/org/pentaho/reporting/libraries/base/util/XMLParserFactoryProducer.java, libraries/libxml/source/org/pentaho/reporting/libraries/xmlns/parser/DomTreeResourceFactory.java
@mbatchelor, @mkambol, could you please take a look?
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

libraries/libxml/source/org/pentaho/reporting/libraries/xmlns/writer/XmlWriterSupport.java, libraries/libxml/test-src/org/pentaho/reporting/libraries/xmlns/writer/XmlWriterSupportTest.java
org.owasp.encoder was included instead custom XML encoding
=> PRD-5776 Unable to open saved prpt report having Japanese surrogate characters

libraries/libxml/source/org/pentaho/reporting/libraries/xmlns/writer/XmlWriterSupport.java
XmlWriterSupport API was restored
=> PRD-5776  Unable to open saved prpt report having Japanese surrogate characters

engine/core/source/org/pentaho/reporting/engine/classic/core/layout/richtext/HtmlRichTextConverter.java
=> Display HTML links within Report Designer elements

libraries/libxml/source/org/pentaho/reporting/libraries/xmlns/writer/XmlWriterSupport.java, libraries/libxml/test-src/org/pentaho/reporting/libraries/xmlns/writer/XmlWriterSupportTest.java
org.owasp.encoder was included instead custom XML encoding
=> SP-3128 PRD-5776 Unable to open saved prpt report having Japanese surrogate characters

libraries/libxml/source/org/pentaho/reporting/libraries/xmlns/writer/XmlWriterSupport.java, libraries/libxml/test-src/org/pentaho/reporting/libraries/xmlns/writer/XmlWriterSupportTest.java
org.owasp.encoder was included instead custom XML encoding
=> SP-3129 PRD-5776 Unable to open saved prpt report having Japanese surrogate characters

libraries/libbase/ivy.xml, libraries/libbase/source/org/pentaho/reporting/libraries/base/util/SystemInformation.java, libraries/libbase/test-src/org/pentaho/reporting/libraries/base/util/SystemInformationTest.java
Cleaned up SystemInformation.java
Fixed bug and added unit tests
=> [PRD-5563] - Bold font in windows menu

engine/core/source/org/pentaho/reporting/engine/classic/core/layout/richtext/HtmlRichTextConverter.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/layout/HtmlRichTextProcessingTest.java
- added rendering for <ol>,<ul>
=> [PRD-5236]-HTML ordered (<ol>) and unordered (<ul>) lists are not respected when rich-text-type = text/html

engine/core/source/org/pentaho/reporting/engine/classic/core/layout/richtext/HtmlRichTextConverter.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/layout/HtmlRichTextProcessingTest.java
- added rendering for <ol>,<ul>
=> [SP-3240][PRD-5236]-HTML ordered (<ol>) and unordered (<ul>) lists are not respected when rich-text-type = text/html

engine/core/source/org/pentaho/reporting/engine/classic/core/layout/richtext/HtmlRichTextConverter.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/layout/HtmlRichTextProcessingTest.java
- added rendering for <ol>,<ul>
=> [SP-3241][PRD-5236]-HTML ordered (<ol>) and unordered (<ul>) lists are not respected when rich-text-type = text/html

engine/legacy-charts/ivy.xml, engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/RadarChartExpression.java, engine/legacy-charts/test-src/org/pentaho/plugin/jfreereport/reportcharts/RadarChartExpressionTest.java
- now series-color applied to RadarChart
=> [PRD-3427]-The specified series-color is not applied to Radar Chart

engine/legacy-charts/ivy.xml, engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/RadarChartExpression.java, engine/legacy-charts/test-src/org/pentaho/plugin/jfreereport/reportcharts/RadarChartExpressionTest.java
- now series-color applied to RadarChart
=> [SP-3259][PRD-3427]-The specified series-color is not applied to Radar Chart

engine/legacy-charts/ivy.xml, engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/RadarChartExpression.java, engine/legacy-charts/test-src/org/pentaho/plugin/jfreereport/reportcharts/RadarChartExpressionTest.java
- now series-color applied to RadarChart
=> [SP-3260][PRD-3427]-The specified series-color is not applied to Radar Chart

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/ReportDesignerInfo.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/ClassicEngineInfo.java, engine/demo/src/main/java/org/pentaho/reporting/engine/classic/demo/ClassicEngineDemoInfo.java, engine/extensions/src/main/java/org/pentaho/reporting/engine/classic/extensions/ClassicEngineExtensionsInfo.java, libraries/configuration-editor/src/main/java/org/pentaho/reporting/tools/configeditor/ConfigEditorInfo.java, pom.xml
=> [BACKLOG-12334] Fix release version missing in the splash screen

engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/AbstractChartExpression.java, engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/CategoricalChartExpression.java, engine/legacy-charts/source/org/pentaho/plugin/jfreereport/reportcharts/XYChartExpression.java, engine/legacy-charts/test-src/org/pentaho/plugin/jfreereport/reportcharts/CategoricalChartExpressionTest.java
* Removing standard tick units that do not match Format precision
* Bar charts also fixed
* Unit test
=> [SP-3402][PRD-5821]  XY Line Chart Y-Tick-Interval Default Behavior for Small Data Ranges

assemblies/mac/src/main/resources/resource/resources/report-designer.properties, assemblies/winlinux/src/main/resources/resource/resources/report-designer.properties, designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/actions/ValidateLoginTask.java, designer/report-designer-extension-pentaho/src/main/resources/org/pentaho/reporting/designer/extensions/pentaho/repository/configuration.properties, designer/report-designer-extension-pentaho/src/test/java/org/pentaho/reporting/designer/extensions/pentaho/repository/actions/ValidateLoginTaskFastTest.java, designer/report-designer-extension-pentaho/src/test/java/org/pentaho/reporting/designer/extensions/pentaho/repository/actions/ValidateLoginTaskTest.java
A new implementation + a flag to enable the old one + tests
=> [PRD-3638]-Check the platform credentials faster

assemblies/winlinux/src/main/resources/resource/report-designer.bat
added - Dswing.useSystemFontSettings=false to report-designer.bat this will keep java from changing the font settings to System
=> [PDR-5563]

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/rtf/itext/PatchRtfTable.java
=> [SP-3418][PRD-5878]-Remove element from a list, the right way

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/rtf/itext/PatchRtfTable.java
=> [SP-3419][PRD-5878]-Remove element from a list, the right way

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/HSSFCellStyleProducer.java, pom.xml
@pentaho/2-1b 
- Updated poi to 3.15
- Added commons-collections4
More info on the jira case.
=> [BACKLOG-15879] Upgrade org.apache.poi components

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/HSSFCellStyleProducer.java, pom.xml
Reverts pentaho/pentaho-reporting#945
=> Revert "[BACKLOG-15879] Upgrade org.apache.poi components"

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/csv/CSVTableExportTask.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/html/HtmlStreamExportTask.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/pdf/PdfExportTask.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/rtf/RTFExportTask.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/xls/ExcelExportTask.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/xls/XSSFExcelExportTask.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/HtmlReportUtil.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/ExportTaskCommon.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/csv/CSVTableExportTaskTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/html/HtmlPagedExportTaskTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/html/HtmlStreamExportTaskTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/pdf/PDFExportTaskTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/rtf/RTFExportTaskTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/xls/ExcelExportTaskTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/xls/XSSFExcelExportTaskTest.java
- added processing new paratemer "create parent folder"
- added unit tests
=> [PDI-14571]-PDI Pentaho Reporting Output Sample does not generate pdf

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/actions/elements/MorphAction.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/actions/elements/MorphActionTest.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/core/actions/ProtectedMethodHelper.java
- simple element shouldn't be convert into complex element such as TableOfContent
=> [PRD-5882]-When double click in a table of contents shows an error message

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/actions/elements/MorphAction.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/actions/elements/MorphActionTest.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/core/actions/ProtectedMethodHelper.java
- simple element shouldn't be convert into complex element such as TableOfContent
- add unit test
=> [SP-3530][PRD-5882]-When double click in a table of contents shows an error message

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/wizard/AggregateFieldPreProcessor.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/wizard/AggregateFieldPreProcessorTest.java
=> [PIR-1338]-Interactive report with 4 or more columns to group gives wrong total

assemblies/mac/src/main/resources/resource/report-designer-debug.bat, assemblies/mac/src/main/resources/resource/report-designer.bat, assemblies/mac/src/main/resources/resource/report-designer.sh, assemblies/mac/src/main/resources/resource/set-pentaho-env.bat, assemblies/mac/src/main/resources/resource/set-pentaho-env.sh, assemblies/winlinux/src/main/resources/resource/report-designer-debug.bat, assemblies/winlinux/src/main/resources/resource/report-designer.bat, assemblies/winlinux/src/main/resources/resource/report-designer.sh, assemblies/winlinux/src/main/resources/resource/set-pentaho-env.bat, assemblies/winlinux/src/main/resources/resource/set-pentaho-env.sh, engine/demo/pentaho-reporting-demo.sh, engine/samples/Sample1.bat, engine/samples/Sample1.sh, engine/samples/Sample2.bat, engine/samples/Sample2.sh, engine/samples/Sample3.bat, engine/samples/Sample3.sh
=> [PSW-229] Script files don't have an header with Copyright data

pom.xml
=> [BACKLOG-13189] GAV change for kettle-xml-plugin

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/wizard/AggregateFieldPreProcessor.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/wizard/AggregateFieldPreProcessorTest.java
=> [SP-3538][PIR-1338]-Interactive report with 4 or more columns to group gives wrong total

engine/core/source/org/pentaho/reporting/engine/classic/core/wizard/AggregateFieldPreProcessor.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/wizard/AggregateFieldPreProcessorTest.java
=> [SP-3539][PIR-1338]-Interactive report with 4 or more columns to group gives wrong total

assemblies/pom.xml, engine/extensions-kettle/pom.xml, pom.xml
DO NOT MERGE prior to merge of kettle mavenization!
=> [BACKLOG-12995] changes for upstream kettle mavenization

engine/legacy-charts/src/main/java/org/pentaho/plugin/jfreereport/reportcharts/ColorHelper.java, engine/legacy-charts/src/main/resources/org/pentaho/plugin/jfreereport/reportcharts/configuration.properties, engine/legacy-charts/src/test/java/org/pentaho/plugin/jfreereport/reportcharts/ColorHelperTest.java
- Added a feature-switch to the reporting configuration
=> [PRD-3023]-Named color code for elements is NOT the same for chart.

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/PreviewParametersDialog.java
users from entering parameters when long parameter list
=> [PRD-3383]-Parameter Dialog on PRD-exports has no scrollbars, prevents

pom.xml
@pentaho/rogueone @pentaho/rebelalliance @tmorgner 
Driver version upgrade. please review.
=> [BACKLOG-17345] Upgrade Postgres JDBC Driver version to 42.1.1

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/PentahoPathModel.java, designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/swing/SwingRemoteDrillDownController.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/DrillDownFunctionParameterEditor.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/basic/DefaultXulDrillDownController.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/model/DrillDownModel.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/swing/SwingGenericUrlDrillDownUi.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/swing/SwingSelfDrillDownUi.java
=> [SP-3738] Backport of PRD-3954 - DRILLDOWN Formula Editor, the Location resets unexpectedly (7.1 Suite)

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/PreviewParametersDialog.java
users from entering parameters when long parameter list
=> [SP-3697]-Parameter Dialog on PRD-exports has no scrollbars, prevents

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/base/PreviewParametersDialog.java
users from entering parameters when long parameter list
=> [SP-3383]-Parameter Dialog on PRD-exports has no scrollbars, prevents

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/welcome/WelcomePane.java
- repostioned buttons to conform with new background image
=> [BACKLOG-18840] - PRD: Logo in initial popup to be the Hitachi logo instead of the Pentaho one

designer/report-designer/pom.xml, designer/report-designer/src/main/resources-filtered/org/pentaho/reporting/designer/core/report-designer.properties
@pentaho/2-1b @pentaho/millenniumfalcon please review
=>  [BACKLOG-19262] Update In-Product Links to Documentation

assemblies/mac/src/assembly/assembly.xml, assemblies/pom.xml, assemblies/winlinux/src/assembly/assembly.xml
=> [BACKLOG-19525] retrieve OSS Licenses from assembly

designer/report-designer/pom.xml, libraries/configuration-editor/pom.xml, libraries/libbase/pom.xml, libraries/libcss/pom.xml, libraries/libdocbundle/pom.xml, libraries/libfonts/pom.xml, libraries/libformat/pom.xml, libraries/libformula-ui/pom.xml, libraries/libformula/pom.xml, libraries/libloader/pom.xml, libraries/libpensol/pom.xml, libraries/libpixie/pom.xml, libraries/librepository/pom.xml, libraries/libserializer/pom.xml, libraries/libsparkline/pom.xml, libraries/libswing/pom.xml, libraries/libxml/pom.xml, pom.xml
@smaring @pentaho/2-1b Please review.
=> [CLEANUP] Use the Implementation-ProductID for the manifest defined in the parent pom by default

libraries/libformula/pom.xml
@pentaho/2-1b @smaring pls review
=> [CLEANUP] adds back the libformula tests classifier

license/templates/licenseHeader.txt
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

assemblies/pom.xml, pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-1757] version name consolidation

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/dialogs/RepositoryPublishDialog.java, designer/report-designer-extension-pentaho/src/main/resources/org/pentaho/reporting/designer/extensions/pentaho/repository/messages.properties
[PDI-16591] Able to import Job/Trans to /<root>
don't allow to publish a file to /<root> of the pentaho repository
=> [PDI-16591] Able to import Job/Trans to /<root>

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/dialogs/RepositoryPublishDialog.java, designer/report-designer-extension-pentaho/src/main/resources/org/pentaho/reporting/designer/extensions/pentaho/repository/messages.properties
[SP-3967][PDI-16591] Able to import Job/Trans to /<root>
don't allow to publish a file to /<root> of the pentaho repository
@bmorrise Could you please review and merge it?
=> [SP-3967][PDI-16591] Able to import Job/Trans to /<root>

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/dialogs/RepositoryPublishDialog.java, designer/report-designer-extension-pentaho/src/main/resources/org/pentaho/reporting/designer/extensions/pentaho/repository/messages.properties
[SP-3966][PDI-16591] Able to import Job/Trans to /<root>
don't allow to publish a file to /<root> of the pentaho repository
=> [SP-3966][PDI-16591] Able to import Job/Trans to /<root>

designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages.properties
@lgrill-pentaho @emartin-pentaho
=> [PPP-3983] change splash screen from Pentaho to HV

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-kettle/pom.xml, designer/report-designer/pom.xml, designer/wizard-xul/pom.xml, pom.xml
@pentaho/2-1b 
Depends on https://github.com/pentaho/pentaho-commons-xul/pull/143
=> [BACKLOG-20423] Update downstreams

engine/extensions-pentaho-metadata/pom.xml, pom.xml
@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186
=> [BACKLOG-13306] GAV change

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/xls/FastExcelPrinter.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/xls/FastExcelPrinterTest.java
=> [CLEANUP] change Pentaho to Hitachi Vantara and update copyright date.

engine/core/pom.xml, pom.xml
@pentaho/x-wing 
Depends on https://github.com/pentaho/pentaho-commons-database/pull/149
=> [BACKLOG-20414] pentaho-commons-database downstream update

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelCellStyleBuilder.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelFontFactory.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelImageHandler.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/HSSFCellStyleProducer.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/HSSFFontWrapper.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelCellStyleBuilderTest.java, pom.xml
@duarteteixeira @pamval @mbatchelor @tmorgner
=> [PPP-4019] Use of vulnerable component Apache POI 3.15 CVE-2017-12626

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/actions/global/NewReportAction.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/core/actions/global/NewReportActionTest.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/AbstractReportDefinition.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/AttributeNames.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/states/process/ProcessState.java, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/metadata/global-meta-elements.xml, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/metadata/messages.properties, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/states/process/ProcessStateTest.java
- queryLimit will be used form the parent state if it is provided and from subreport's attributes otherwise
=> [PRD-5952] PRPT : Row Limit "No More Than" is not getting applied to Sub reports.

libraries/libformula-ui/src/test/java/org/pentaho/openformula/ui/FormulaEditorPanelTest.java
@tmorgner, as request on https://jira.pentaho.com/browse/PRD-4692
=> [PRD-4692] Fix FormulaEditorPanelTests - One fails always, one randomly

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/actions/global/NewReportAction.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/core/actions/global/NewReportActionTest.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/AbstractReportDefinition.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/AttributeNames.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/states/process/ProcessState.java, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/metadata/global-meta-elements.xml, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/metadata/messages.properties, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/states/process/ProcessStateTest.java
=> [SP-4235] Backport of PRD-5952 - PRPT : Row Limit "No More Than" is not getting applied to Sub reports.

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/actions/global/NewReportAction.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/core/actions/global/NewReportActionTest.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/AbstractReportDefinition.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/AttributeNames.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/states/process/ProcessState.java, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/metadata/global-meta-elements.xml, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/metadata/messages.properties, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/states/process/ProcessStateTest.java
=> [SP-4234] Backport of PRD-5952 - PRPT : Row Limit "No More Than" is not getting applied to Sub reports.

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/actions/PublishToServerTask.java, designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/util/PublishUtil.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/PublishRestUtil.java
=> [PRD-5569]-Published Report's Filename is Displayed instead of Title in

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactory.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactoryTest.java
- new conditions for the String parameters processing were added
- new tests were added
=> [PDB-2004] SQL List Prompts are converting parameters based on string to double precision numbers

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/actions/PublishToServerTask.java
@tmorgner 
To fix the problem introduced by PRD-5569
=> [BACKLOG-22676] Errors displays when publishing report from PRD to server

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/output/AbstractOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/text/TextUtility.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelOutputProcessorMetaData.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/layout/text/TextUtilityTest.java
=> [PRD-5435] Excel Output - Dynamic height setting is not applied

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/DefaultStyleBuilder.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/DefalutStyleBuilderTest.java
-map to the nearest equivalent
=> [PRD-5989]-Horizontal line is not visible in HTML when the line is dashed, dotted, dot-dash or dot-dot-dashed

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactory.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactoryTest.java
=> [SP-4284] Backport of PDB-2004 - SQL List Prompts are converting parameters based on string to double precision numbers (8.0 Suite)

designer/datasource-editor-jdbc/src/main/java/org/pentaho/reporting/ui/datasources/jdbc/ui/JdbcQueryDesignerDialog.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactory.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactoryTest.java
@tmorgner 
**Note for future reference (SP's process): This commit uses code made in context of https://jira.pentaho.com/browse/BACKLOG-23781 (already merged), please respect this order**
=> [PRD-4896] SQL Query Designer Preview button not working

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/parameters/Messages.java, libraries/libbase/pom.xml, libraries/libbase/src/main/java/org/pentaho/reporting/libraries/base/util/ResourceBundleSupport.java
Reverts pentaho/pentaho-reporting#1167
=> Revert "[PIR-1172] - L10N - Untranslated string in PIR prompt."

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/parameters/DefaultReportParameterValidator.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/parameters/FormulaParameterEvaluator.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/parameters/Messages.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/parameters/ParameterUtils.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/parameters/ParameterUtilsTest.java
* Messages handling mechanism changed from singleton to multi instance.
* Pentaho's platform configured locale is now used to get the correct language.
=> [PIR-1172] - L10N - Untranslated string in PIR prompt.

assemblies/pom.xml, pom.xml
Reverts pentaho/pentaho-reporting#1172
@pentaho/r2d2 
@emartin-pentaho @pentaho-amessier
=> Revert "[BACKLOG-24588] Removing references to the kettle-json-plugin from assemblies"

designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages.properties
=> [SP-4506] - Backport of PRD-6024 - Copyright info on PRD not okay

designer/datasource-editor-jdbc/pom.xml, designer/report-designer/pom.xml, designer/wizard-xul/pom.xml, engine/extensions-kettle/pom.xml, pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

libraries/pom.xml, pom.xml
Homogenize the pom profile refactor started in the previous commit
=> [CLEANUP] Follow up conversion for profiles in poms

libraries/libformula-ui/src/test/java/org/pentaho/openformula/ui/FormulaDocumentTest.java
=> [CLEAN UP] Remove unused import

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/PentahoParameterRefreshHandler.java
- cherry-pick https://github.com/pentaho/pentaho-reporting/pull/1204 into 8.2 branch
@pamval @kcruzada @pentaho-jlien @pentaho-svigneri please review/process
CC'ing @pentaho-lmartins @pentaho/rogueone
=> Backlog 26393 8.2

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/PentahoParameterRefreshHandler.java
- cherry-pick https://github.com/pentaho/pentaho-reporting/pull/1204 into 8.2.0.0 branch
@pamval @kcruzada @pentaho-jlien @pentaho-svigneri please review/process
CC'ing @pentaho-lmartins @pentaho/rogueone
=> Backlog 26393 8.2.0.0

assemblies/samples/pom.xml, assemblies/samples/src/assembly/assembly.xml
Fix to allow Ciren to produce correct artifacts
@jmcrfp
=> [PPP-4167] - Fix on assembly "pre-classic-sdk"

assemblies/samples/pom.xml, assemblies/samples/src/assembly/assembly.xml
Reverts pentaho/pentaho-reporting#1210
=> Revert "[SP-4786] - Backport of PPP-4167 - Assembly "pre-classic-sdk" seems t…"

assemblies/samples/Sample1.sh, assemblies/samples/Sample2.sh, assemblies/samples/Sample3.sh, assemblies/samples/src/assembly/assembly.xml
Fix's to bugs found by Vitor when trying to back port base correction to 7.1
@cardosov
=> [PPP-4167] - Linux fix on assembly "pre-classic-sdk"

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, designer/report-designer-extension-legacy-charts/pom.xml, designer/report-designer-extension-pentaho/pom.xml, designer/report-designer-extension-toc/pom.xml, designer/report-designer-extension-wizard/pom.xml, engine/demo/pom.xml, engine/extensions-pentaho-metadata/pom.xml, engine/extensions-reportdesigner-parser/pom.xml, engine/testcases/pom.xml, engine/tools/pom.xml, pom.xml
This is a series of PRs, please see pentaho/maven-parent-poms#82 for full list.
@ssamora
=> [PPP-4226] Use of vulnerable component commons-compress  CVE-2018-11771

assemblies/prd-ce/src/main/resources/resource/Pentaho Report Designer.app/Contents/Info.plist
=> [BACKLOG-26968] Update copyright versions to 2019

assemblies/prd-ce/src/main/resources/resource/Pentaho Report Designer.app/Contents/Info.plist
=> [SP-4856] Backport of BACKLOG-26968 - Update copyright versions to 2019

assemblies/mac/src/main/resources/mac/Contents/Info.plist
=> [SP-4857] Backport of BACKLOG-26968 - Update copyright versions to 2019

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/csv/CsvTemplateProducer.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/csv/CsvTemplateProducerTest.java
@LeonardoCoelho71950 @ssamora @pentaho/tatooine
=> [SP-4883] Backport of PRD-5412 - CSV Output changes the alignment of header row and adds a trailing separator to the report (7.1 Suite)

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/csv/CsvTemplateProducer.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/csv/CsvTemplateProducerTest.java
@LeonardoCoelho71950 @ssamora @pentaho/tatooine
=> [SP-4884] Backport of PRD-5412 - CSV Output changes the alignment of header row and adds a trailing separator to the report (8.2 Suite)

assemblies/prd-ce/src/main/resources/resource/samples/metadata.xmi, engine/extensions-pentaho-metadata/src/test/resources/metadata/metadata.xmi
=> [PMD-1095] Security Service displays joe user

pom.xml
@graimundo 
There was a problem with the lastest rebase. Those dependencies were already removed:
- https://github.com/ricardosilva88/pentaho-reporting/commit/67fd677325b5abad2ef540056021d3f0cfd6276e#diff-600376dffeb79835ede4a0b285078036
- https://github.com/pentaho/pentaho-reporting/commit/67fd677325b5abad2ef540056021d3f0cfd6276e#diff-600376dffeb79835ede4a0b285078036L993
=> [PPP-4223] - Fixing problem with rebase

pom.xml
Reverts pentaho/pentaho-reporting#1254
=> Revert "[PPP-4271] - Fixed Use of Vulnerable Component: xercesImpl-2.11.0 and…"

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/parameters/ParameterDialog.java, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/editor/parameters/messages/messages.properties, designer/report-designer/src/test/java/org/pentaho/reporting/designer/core/editor/parameters/ParameterDialogTest.java, engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/ParameterReportControllerPane.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/PreviewParametersDialog.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/parameters/ParameterAttributeNames.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/ParameterReportControllerPaneTest.java
@pentaho/bobafett please review
=> [BACKLOG-26682] As a report designer, i would like to hide parameters based on a formula

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/text/FixedFunction.java, libraries/libformula/src/main/resources/org/pentaho/reporting/libraries/formula/function/text/Fixed-Function.properties, libraries/libformula/src/test/java/org/pentaho/reporting/libraries/formula/function/text/FixedFunctionTest.java
@pentaho/tatooine @pentaho-lmartins @ssamora
=> [PRD-6065] Fix libformula FIXED function with 3rd parameter

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/text/DollarFunction.java, libraries/libformula/src/test/java/org/pentaho/reporting/libraries/formula/function/text/DollarFunctionTest.java
@pentaho/tatooine @pentaho-lmartins @ssamora
=> [PRD-6064] Fix libformula DOLLAR function

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/math/AcoshFunction.java, libraries/libformula/src/test/java/org/pentaho/reporting/libraries/formula/function/math/AcoshFunctionTest.java
@pentaho/tatooine @pentaho-lmartins @ssamora
=> [PRD-6063] Fix libformula ACOSH function to return correct value

assemblies/prd-ce/pom.xml, pom.xml
=> [BACKLOG-29708] - PRD-CE assembly - Migrating from deprecated old style

engine/extensions-kettle/pom.xml, engine/extensions-pentaho-metadata/pom.xml, pom.xml
@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17794] Removing dependencies due to being marked as unused and declared via dependency:analyze (engine/extensions-kettle/pom.xml, engine/extensions-pentaho-metadata/pom.xml, pom.xml)
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- https://github.com/webdetails/cpk/pull/82
- https://github.com/pentaho/data-access/pull/1060
- https://github.com/pentaho/maven-project-archetypes/pull/16
- …
=> [PDI-17794] Warnings in Spoon console due to wrong version of log4j

engine/extensions-drilldown/pom.xml, engine/extensions-drilldown/src/main/java/org/pentaho/reporting/engine/classic/extensions/drilldown/PatternLinkCustomizer.java, engine/extensions-drilldown/src/main/resources/org/pentaho/reporting/engine/classic/extensions/drilldown/drilldown-profile.xml, engine/extensions-drilldown/src/test/java/org/pentaho/reporting/engine/classic/extensions/drilldown/PatternLinkCustomizerTest.java
@pentaho-lmartins @pentaho/tatooine
=> [PRD-6069] Pentaho Report Designer Hyperlink adds ? automatically

engine/extensions-drilldown/pom.xml, engine/extensions-drilldown/src/main/java/org/pentaho/reporting/engine/classic/extensions/drilldown/PatternLinkCustomizer.java, engine/extensions-drilldown/src/main/resources/org/pentaho/reporting/engine/classic/extensions/drilldown/drilldown-profile.xml, engine/extensions-drilldown/src/test/java/org/pentaho/reporting/engine/classic/extensions/drilldown/PatternLinkCustomizerTest.java
Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/pentaho/pentaho-reporting/commit/0b2397068a62b9633ad3f6129a48c0e692aeab94
=> [SP-5320] Backport of PRD-6069 - Pentaho Report Designer Hyperlink adds ? automatically (8.3 Suite)

designer/wizard-xul/src/main/java/org/pentaho/reporting/engine/classic/wizard/ui/xul/steps/LookAndFeelStep.java
=> [PRD-5292] Fix Report Wizard Template selection Bug

designer/datasource-editor-jdbc/pom.xml, engine/extensions-kettle/pom.xml, libraries/libloader/pom.xml, pom.xml
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PDI-17775] Cleaning up version references to old commons-vfs2, unifying under maven parent pom. Removing unused, declared dependency reference.
* [PDI-17775] Removing version reference, maven parent pom will control version.
* [PDI-17775] version reference remains at top-level pom and points to maven-parent-pom parameter due to dependencyManagement tags overriding maven-parent-pom, version control is still owned by maven-parent-pom
This PR is a part of a series of PR to upgrade commons-vfs2 and fix VFS issues with HTTP:
- https://github.com/pentaho/apache-vfs-browser/pull/60
- https://github.com/pentaho/big-data-plugin/pull/1929
- https://github.com/webdetails/cpk/pull/85
- https://github.com/pentaho/data-access/pull/1083
- …
=> [PDI-17775] Process Files step no longer supports HTTP scheme

libraries/libloader/pom.xml
=> [PDI-18566] Fixing test dependencies

libraries/libloader/src/test/java/org/pentaho/reporting/libraries/resourceloader/loader/fileobject/FileObjectResourceLoaderTest.java
=> [PDI-18566] making unit test agnostic to OS

libraries/libloader/src/test/java/org/pentaho/reporting/libraries/resourceloader/loader/fileobject/FileObjectResourceLoaderTest.java
=> [SP-5493] making unit test agnostic to OS

README.md, designer/report-designer/README.txt, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/actions/messages/messages.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/actions/messages/messages_ja.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages_ja.properties, engine/core/README.md
=> [PRD-6114] Online Forum link is not working

README.md, designer/report-designer/README.txt, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/actions/messages/messages.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/actions/messages/messages_ja.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages_ja.properties, engine/core/README.md
cherry-pick of: 
#1360
#1361
Added 2 commits since master had 2 distinct PRs.
Please review and **squash** merge
@ssamora
=> [SP-5686] Backport of PRD-6114 - Online Forum link is not working (8.3 Suite)

README.md, designer/report-designer/README.txt, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/actions/messages/messages.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/actions/messages/messages_ja.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages.properties, designer/report-designer/src/main/resources/org/pentaho/reporting/designer/core/messages/messages_ja.properties, engine/core/README.md
cherry-pick of: 
#1360
#1361
Added 2 commits since master had 2 distinct PRs.
Please review and **squash** merge.
@ssamora
=> [SP-5687] Backport of PRD-6114 - Online Forum link is not working (9.0 Suite)

assemblies/prd-ce/src/main/resources-filtered/report-designer.sh
Please note that this is an masOS and Ubuntu issue.
Additional PR https://github.com/pentaho/pentaho-reportdesigner-ee/pull/159
@ssamora 
@ppatricio
=> [PRD-6100] - PRD startup script throws some errors (Ubuntu & MacOS)

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/typing/DefaultTypeRegistry.java
=> [PDI-18402] - Formula step not considering the metadata of the column when performing the logical operations.

engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/bugs/Prd2262IT.java, engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/bugs/Prd3239IT.java, engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/bugs/Prd3857IT.java, engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/bugs/Prd4215IT.java, engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/modules/output/pageable/pdf/PdfEncryptionValidateIT.java, engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/states/ValidateStateIT.java, libraries/libpensol/src/it/java/org/pentaho/reporting/libraries/pensol/PublishRestUtilTestIT.java
spot new problems.  Backlog item will be created to fix these.
=> [CLEANUP] Ignoring tests that have been failing for a long time to help

designer/datasource-editor-table/src/main/java/org/pentaho/reporting/ui/datasources/table/ImportFromFileTask.java, engine/core/pom.xml, engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/bugs/Prd3278IT.java, engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/bugs/Prd4434IT.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelImageHandler.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinterBase.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/HSSFCellStyleProducer.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/StaticExcelColorSupport.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/table/excel/ExcelColorSupportTest.java, pom.xml
Cherry pick of:
- [pentaho-reporting#1380](https://github.com/pentaho/pentaho-reporting/pull/1380)
- [pentaho-reporting#1381](https://github.com/pentaho/pentaho-reporting/pull/1381)
@ssamora @bcostahitachivantara @moraesvc
=> [SP-5994] Backport of PPP-4590 - XML External Entity (XXE) vulnerability when reading XLSX files (8.3 Suite)

libraries/libformat/src/test/java/org/pentaho/reporting/libraries/formatting/DateFormatTest.java, libraries/libformat/src/test/java/org/pentaho/reporting/libraries/formatting/MessageFormatTest.java
Reverts pentaho/pentaho-reporting#1422
=> Revert "[BACKLOG-35287] Unit test fixes for JDK11 upgrade."

engine/core/pom.xml, engine/extensions-scripting/pom.xml, engine/legacy-charts/pom.xml
=> [CUST-258] - Update Pom versions

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/beanshell/BSHExpression.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/bsf/BSFExpression.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/bsf/BSFReportPreProcessor.java, engine/core/src/test/resources/classic-engine.properties, engine/extensions-scripting/pom.xml, engine/extensions-scripting/src/main/java/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/ScriptableDataFactory.java, engine/legacy-charts/pom.xml, engine/legacy-charts/src/main/java/org/pentaho/plugin/jfreereport/reportcharts/AbstractChartExpression.java
@smmribeiro 
@ssamora 
@renato-s
=> [CUST-259] - Requesting a CUST for the Critical Flaws Uncovered in Pentaho (v9.0.0.7)

engine/extensions-scripting/pom.xml, engine/legacy-charts/pom.xml
@ssamora 
@smmribeiro 
@renato-s
=> [CUST-259] - Update Pom versions

pom.xml
=> [BACKLOG-35399] - Update projects to include locale properties for integration test execution

libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/loader/URLResourceLoader.java, libraries/libloader/src/test/java/org/pentaho/reporting/libraries/resourceloader/loader/URLResourceLoaderTest.java
=> [CDF-946] PRD+CGG not working when there is a space in the parameter value

engine/extensions-kettle/pom.xml, engine/extensions-pentaho-metadata/pom.xml, pom.xml
This commit is a cherry-pick from 8.3 c1b664c4d
=> [SP-6106] backport of BISERVER-14720 - Upgrade log4j2

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinter.java
@smmribeiro 
@renato-s 
@bcostahitachivantara
=> [SP-6077] Backport of PRD-6134 - Output to Excel does not create Excel footer if more than a certain number of records are on the sheet

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinter.java
@smmribeiro 
@renato-s 
@bcostahitachivantara
=> [SP-6076] Backport of PRD-6134 - Output to Excel does not create Excel footer if more than a certain number of records are on the sheet

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinter.java
@smmribeiro 
@renato-s 
@bcostahitachivantara
=> [SP-6077] Backport of PRD-6134 - Output to Excel does not create Excel footer if more than a certain number of records are on the sheet #1503

assemblies/prd-ce/pom.xml
=> [BACKLOG-35888] Include metastore locator and repository locator

assemblies/prd-ce/pom.xml
declaration per plugin per profile.
=> [BACKLOG-36155] Consolidate duplicate plugin declarations into one

pom.xml
this is for the backporting from the original commit - c35349ece099cceb444d0a09571f01167f501967
=> [PPP-4654] Get commons-io version from parent pom

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactory.java
=> [PPP-4765] - Full SQL Query is shown on PUC when PRD fails

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactory.java
Original PR:
- https://github.com/pentaho/pentaho-reporting/pull/1517
@andreramos89 
@smmribeiro
=> [SP-6204] - Backport of PPP-4765 - Full SQL Query is shown on PUC when PRD fails (9.3 Suite)

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, pom.xml
@bcostahitachivantara @renato-s @andreramos89
=> [PPP-4783] Vulnerable Component: nekohtml

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/CustomErrorValue.java
=> [PDI-19716] - "ERROR" Function in Formula step is not working as expected.

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, pom.xml
=> [PPP-4828] - Component Rome is outdated

engine/core/modules.txt, engine/core/pom.xml, pom.xml
@smmribeiro 
@andreramos89 
@renato-s
=> [PPP-3713] - Beanshell version we're using is vulnerable to serialization exploit - CVE-2016-2510

engine/core/pom.xml, pom.xml
=> [BACKLOG-37531] Update to latest bouncycastle dependencies and

engine/core/pom.xml, pom.xml
standardize across products.
This commit is a cherry-pick from master 6c8ab8f
=> [BACKLOG-37531] Update to latest bouncycastle dependencies and (#1560)

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/CustomErrorValue.java
@andreramos89 
@smmribeiro 
Original PR: https://github.com/pentaho/pentaho-reporting/pull/1547
=> [SP-6338] - Backport of PDI-19716 - "ERROR" Function in Formula step is not working as expected. (9.3 Suite)

engine/legacy-charts/src/main/java/org/pentaho/plugin/jfreereport/reportcharts/ExtendedXYLineChartExpression.java, engine/legacy-charts/src/main/java/org/pentaho/plugin/jfreereport/reportcharts/XYAreaChartExpression.java, engine/legacy-charts/src/main/java/org/pentaho/plugin/jfreereport/reportcharts/XYBarChartExpression.java, engine/legacy-charts/src/main/java/org/pentaho/plugin/jfreereport/reportcharts/XYLineChartExpression.java
Original PR:
- https://github.com/pentaho/pentaho-reporting/pull/1578
=> [SP-6418] - Backport of PRD-5303 - XY Area Chart chart display issues (9.3 Suite)

pom.xml
[PPP-4747] Vulnerable Component: batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4747] Vulnerable Component: batik-1.19

pom.xml
@bcostahitachivantara @renato-s @andreramos89
=> [PPP-4981] PRD 9.3.0.4 and above will not launch

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/output/AbstractOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/output/OutputProcessorFeature.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/FlowExcelOutputProcessor.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinter.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinterBase.java, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/config-description.xml, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/configuration.properties
Reverts pentaho/pentaho-reporting#1624
@renato-s @andreramos89
=> Revert "[BISERVER-14865] - Impossible to download PIR reports onto Excel 2007 format once data is past Excel limitations"

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/output/AbstractOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/output/OutputProcessorFeature.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/FlowExcelOutputProcessor.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinter.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinterBase.java, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/config-description.xml, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/configuration.properties
=> [BISERVER-14865] - Impossible to download PIR reports onto Excel 2007 format once data is past Excel limitations

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, pom.xml
=> [PPP-4865] - Vulnerable Component: snakeyaml

engine/extensions-kettle/pom.xml, pom.xml
=> [BACKLOG-40255] Sub in our patched axis2-kernel jar to resolve bytecode

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelCellStyleBuilder.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelFontFactory.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinterBase.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/HSSFCellStyleProducer.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/XSSFExcelColorProducer.java, engine/testcases/pom.xml, pom.xml
=> [PRD-5458] Improve MS Excel export time by switching to streaming version of POI API

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/base/AbstractTableOutputProcessor.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/HtmlContentGenerator.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/HtmlTableModule.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/DefaultHtmlContentGenerator.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/HtmlOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/HtmlTextExtractorHelper.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/StyleBuilder.java, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/modules/output/table/html/configuration.properties
@pentaho/hoth Please review
Part of PR set
https://github.com/pentaho/pentaho-scheduler-plugin/pull/179
https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/244
https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/852
=> [BACKLOG-39678] - Schedule Output Perspective : Improve reporting engine to generate in line style and images for html rendering

assemblies/prd-ce/src/main/resources-filtered/report-designer.sh
=> [BACKLOG-41352] warning and error showing in log when launching PRD in MAC OS

engine/extensions-pentaho-metadata/src/main/java/org/pentaho/reporting/engine/classic/extensions/datasources/pmd/SimplePmdDataFactory.java, engine/extensions-pentaho-metadata/src/main/resources/classic-engine.properties, engine/extensions-pentaho-metadata/src/test/java/org/pentaho/reporting/engine/classic/extensions/datasources/pmd/SimplePmdDataFactoryTest.java
=> [PIR-1523] - SQL queries for the prompts In Interactive reports are executed twice

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinter.java
@pentaho/tatooine_dev please review
=> [PRD-6165] Reset sheet row on new sheet

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, pom.xml
connection pool for hibernate, and tomcat handles that.
=> [PPP-4391] Remove c3p0 dependency; was never really used except as a

designer/datasource-editor-pmd/src/main/java/org/pentaho/reporting/ui/datasources/pmd/PmdDataSourceEditor.java, engine/extensions-kettle/src/main/java/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/DocumentHelper.java, engine/extensions-mondrian/src/main/java/org/pentaho/reporting/engine/classic/extensions/datasources/mondrian/MondrianUtil.java, libraries/configuration-editor/src/main/java/org/pentaho/reporting/tools/configeditor/util/DOMUtilities.java, libraries/libbase/pom.xml, libraries/libbase/src/main/java/org/pentaho/reporting/libraries/base/config/metadata/ConfigurationMetaDataParser.java, libraries/libbase/src/main/java/org/pentaho/reporting/libraries/base/util/XMLParserFactoryProducer.java, libraries/libxml/src/main/java/org/pentaho/reporting/libraries/xmlns/parser/DomTreeResourceFactory.java
[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code
=> [REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

designer/report-designer/pom.xml, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/model/data/ActorSystemHost.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/model/data/AsynchronousDataSchemaManager.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/model/data/QueryMetaDataActorImpl.java, pom.xml
See commit messages and related tickets
https://github.com/pentaho/pentaho-reporting/pull/1697/commits/8d81c411c5b0b78805e951172aa3f823e2b33f5d
https://github.com/pentaho/pentaho-reporting/pull/1697/commits/d657dd1a51a798f5b52fa66b26976b43eed4e013
https://hv-eng.atlassian.net/browse/PPP-4537
https://hv-eng.atlassian.net/browse/SP-6573
=> [SP-6573] Backport of [PPP-4537] - Use of Vulnerable Component: Components/akka (10.2 Suite)

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, pom.xml
- change all references to 'org.yaml:snakeyaml'
- add 'org.yaml:snakeyaml' to assembly
=> [PPP-5163] Vulnerable Component: snakeyaml - part 2 ( Non OSGi upgrade)

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, libraries/libpensol/pom.xml, libraries/libpensol/src/it/java/org/pentaho/reporting/libraries/pensol/PublishRestUtilTestIT.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/JCRSolutionDirectFileModel.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModel.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/PublishRestUtil.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/RepositoryFileTreeDtoProxy.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/JCRRepositoryTest.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModelTest.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/RepositoryFileTreeDtoProxyTest.java, pom.xml
=> [BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

assemblies/prd-ce/pom.xml, assemblies/sample-war/pom.xml, assemblies/sample-war/src/java/org/pentaho/reporting/engine/classic/samples/Sample4.java, assemblies/samples/pom.xml, engine/extensions/pom.xml, engine/extensions/src/it/java/org/pentaho/reporting/engine/classic/extensions/modules/mailer/MailProcessorIT.java, engine/extensions/src/main/java/org/pentaho/reporting/engine/classic/extensions/modules/mailer/DefaultAuthenticator.java, engine/extensions/src/main/java/org/pentaho/reporting/engine/classic/extensions/modules/mailer/MailDefinition.java, engine/extensions/src/main/java/org/pentaho/reporting/engine/classic/extensions/modules/mailer/MailProcessor.java, engine/extensions/src/test/java/org/pentaho/reporting/engine/classic/extensions/modules/mailer/DefaultAuthenticatorTest.java, libraries/libpensol/pom.xml, libraries/libpensol/src/it/java/org/pentaho/reporting/libraries/pensol/PublishRestUtilTestIT.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/JCRSolutionDirectFileModel.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModel.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/PublishRestUtil.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/RepositoryFileTreeDtoProxy.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/JCRRepositoryTest.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModelTest.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/RepositoryFileTreeDtoProxyTest.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/resources/TestRepositoryPublishResource.java, libraries/librepository/pom.xml, libraries/librepository/src/main/java/org/pentaho/reporting/libraries/repository/email/EmailEntryOutputStream.java, libraries/librepository/src/main/java/org/pentaho/reporting/libraries/repository/email/EmailRepository.java, pom.xml
[BACKLOG-41287]-Upgrading Security-Web from Java EE to Jakarta EE to support with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41287]-Upgrading Security-Web from Java EE to Jakarta EE to support with Tomcat-10.X

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/cache/EhCacheDataCache.java, libraries/libloader/pom.xml, libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/modules/cache/ehcache/EHCacheProvider.java, libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/modules/cache/ehcache/EHResourceBundleDataCache.java, libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/modules/cache/ehcache/EHResourceDataCache.java, libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/modules/cache/ehcache/EHResourceFactoryCache.java, pom.xml
[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

assemblies/prd-ce/src/main/resources-filtered/report-designer.bat, assemblies/prd-ce/src/main/resources-filtered/report-designer.sh
=> [PRD-6177] - With Java 17, the property settings in "Edit Chart" with in Report Designer are no longer editable.

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/DefaultHtmlContentGenerator.java
- adding back in check for null dataLocation
This PR supports https://github.com/pentaho/pentaho-kettle/pull/9852
=> [PRD-6184] HTML Streaming Format Fails to Generate Report

assemblies/prd-ce/pom.xml
[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43209]-OSGi Assembly Issues

designer/report-designer-extension-pentaho/pom.xml, engine/core/pom.xml, libraries/libloader/pom.xml, pom.xml
[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
[BACKLOG-43757]: https://hv-eng.atlassian.net/browse/BACKLOG-43757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version

designer/datasource-editor-jdbc/pom.xml, designer/pom.xml, designer/report-designer-extension-pentaho/pom.xml, designer/report-designer-extension-wizard/pom.xml, engine/core/pom.xml, engine/extensions-drilldown/pom.xml, engine/extensions-kettle/pom.xml, engine/extensions-pentaho-metadata/pom.xml, engine/extensions-scripting/pom.xml, engine/extensions-xpath/pom.xml, engine/extensions/pom.xml, engine/legacy-charts/pom.xml, libraries/pom.xml
[BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures
[BACKLOG-43935]: https://hv-eng.atlassian.net/browse/BACKLOG-43935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures

libraries/libpensol/pom.xml, pom.xml
=> feat[PPP-5649]: add/fix optional dependencies

engine/core/src/it/java/org/pentaho/reporting/engine/classic/core/GoldCacheLoadIT.java, engine/extensions/pom.xml, engine/extensions/src/it/java/org/pentaho/reporting/engine/classic/extensions/modules/mailer/MailProcessorIT.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModel.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/PublishRestUtil.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModelTest.java, libraries/libpensol/src/test/java/org/pentaho/reporting/libraries/pensol/RepositoryFileTreeDtoProxyTest.java
[BACKLOG-44959]-Resolving PR review comments in pentaho-reporting
[BACKLOG-44959]: https://hv-eng.atlassian.net/browse/BACKLOG-44959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-44959]-Resolving PR review comments in pentaho-reporting

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml
=> chore[PPP-5719]: upgrade Saxon dependency

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/DataFactoryScriptingSupport.java
=> fix[PPP-5778] partial revert of #1770

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/DataFactoryScriptingSupport.java
This time only for actual scripting
@pentaho/tatooine_dev
=> fix[PPP-5778] Check if scripts are allowed to run

pom.xml
=> fix[PPP-5840]: update Hibernate version and adjust dependency exclusions

assemblies/prd-ce/src/main/resources-standard/resource/system/osgi/log4j2.xml, assemblies/prd-ce/src/main/resources/resource/resources/log4j2.xml
=> chore[PPP-5981]: add monitorInterval to log4j2 configuration

designer/datasource-editor-pmd/src/main/java/org/pentaho/reporting/ui/datasources/pmd/PmdDataSourceEditor.java, engine/extensions-charting/src/main/java/org/pentaho/reporting/engine/classic/extensions/charting/runtime/BaseScope.java
=> fix[PPP-5982]: add proper initialization to XML parser
