libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/JCRSolutionFileModel.java, libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/PentahoSolutionFileProvider.java
- Libpensol now refreshes local tree cache when a new File is created in a JCR repository
- Added WRITE_CONTENT capability to the libpensol PentahoSolutionFileProvider
=> [PRD-5343] - Libpensol now refreshes local tree cache when a new File is created in a JCR repository

engine/legacy-charts/build.properties
@tmorgner, @mdamour1976, could you please merge it? This is needed to enable running tests for the 'legacy-charts' module. Now they are ignored because subfloor.xml defines 'test-src' as a valid name for test folder
=> [TEST] - setting up test folder properly

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/layout/CommonStyleReadHandler.java
cherry-pick https://github.com/pentaho/pentaho-reporting/pull/591
=> SP-1760 - Backport of PRD-5393 - Regression: Report breaks after setting property widow-orphan-opt-out to false on the Group. (5.3 Suite)

engine/core/test/org/pentaho/reporting/engine/classic/core/IvyTest.java
Now reporting the code base for the offending class. CI behaves different than the local build.
=> PRD-5419 - Add test to catch ivy errors early.

designer/datasource-editor-kettle/ivy.xml, engine/extensions-kettle/ivy.xml
@rmansoor please review and merge if this is the correct approach
SettableFuture was added to KettleEnvironment class by https://github.com/pentaho/pentaho-kettle/commit/7bf2b1550d1edb2c924c8d0256e695e36d24cbed - this broke the tests
=> [TEST] - added guava dependency to pass tests

libraries/libformat/test/org/pentaho/reporting/libraries/formatting/DateFormatTest.java, libraries/libformat/test/org/pentaho/reporting/libraries/formatting/MessageFormatTest.java
When running the MessageFormatTest.testNoCrash() unit test, the test would fail with a date that was 1 day off because the message was output as "25 Nov 1973" (25 Nov 1973 19:52:03 EST). Updated the test to check for either 25 or 26 of Nov since the purpose of the test was testing the default constructor.
=> [CLEANUP] Fixed unit test that would fail based on timezone where executed

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/fast/validator/ReportStructureValidator.java, engine/core/test/org/pentaho/reporting/engine/classic/core/bugs/Prd5268Test.java
Backport of https://github.com/pentaho/pentaho-reporting/pull/647
@tmorgner
Please review.
=> SP-2007 - Backport of PRD-5478 - Page header missing in the second page of the excel export (5.4 Suite)

engine/core/test/org/pentaho/reporting/engine/classic/core/bugs/Prd5321Test.java, engine/core/test/org/pentaho/reporting/engine/classic/core/function/aggregate-function-test.xml, engine/core/test/org/pentaho/reporting/engine/classic/core/layout/layouting.xml, engine/core/test/org/pentaho/reporting/engine/classic/core/layout/table/TableLayoutTest.java, engine/core/test/org/pentaho/reporting/engine/classic/core/layout/weird-layouting.xml, engine/core/test/org/pentaho/reporting/engine/classic/core/modules/output/pageable/plaintext/plain-text-export.xml, engine/core/test/org/pentaho/reporting/engine/classic/core/states/validate-page-numbers.xml, engine/core/test/org/pentaho/reporting/engine/classic/core/testsupport/DebugReportRunner.java, libraries/libfonts/libfonts.iml, libraries/libformula/libformula.iml
The Prd5321 test cannot be run safely on a CI machine as it uses local font rendering, and thus requires careful setup. Tests like that probably need to run in a carefully curated test environment, like a VM or so.
GoldenSample tests were failing after an overly eager formatting round on the various XML files changed some property values. Adding new-lines randomly is bound to cause troubles.
Finally: Updated the IntelliJ module files to include the mockito jars used by LibFormula and LibFonts on their classpath.
=> [CLEANUP] - Fixes for some broken tests

engine/core/test/org/pentaho/reporting/engine/classic/core/bugs/Prd5321Test.java, engine/core/test/org/pentaho/reporting/engine/classic/core/layout/table/TableLayoutTest.java, engine/core/test/org/pentaho/reporting/engine/classic/core/testsupport/DebugReportRunner.java, engine/extensions-kettle/ivy.xml
CI did not pick up my exclusion, so now I use the conservative measure of demanding a specific system property to be set before the dangerous tests are run. Ant, or any normal developer, will not have the system property set, so the tests are skipped. 
Kettle tests were failing as we did not pull in VFS2 and Guava via Ivy. The tests are much happier now.
=> [CLEANUP] - More test fixes

designer/report-designer-assembly/resource/resources/log4j.xml
- on startup, and with log level set to DEBUG, PRD dumps > 3k lines to the log
=> [BACKLOG-5203] Change the level of logging for Report Designer

designer/report-designer-assembly/ivy.xml
@mkambol @hudak @dkincade 
conf was changed to copy our driver into the jdbc folder with the other drivers. The plugin conf is no longer needed since a change was made awhile back that added the pdi-client via karaf, so now it gets pick up there.
=> [BACKLOG-5341] Added data service client to drivers folder

engine/core/source/org/pentaho/reporting/engine/classic/core/layout/process/alignment/AbstractAlignmentProcessor.java, libraries/libbase/source/org/pentaho/reporting/libraries/base/boot/DefaultObjectFactory.java, libraries/libbase/source/org/pentaho/reporting/libraries/base/config/DefaultConfiguration.java, libraries/libbase/source/org/pentaho/reporting/libraries/base/util/ObjectUtilities.java, libraries/libbase/testcases/org/pentaho/reporting/libraries/base/boot/ObjectFactoryTest.java, libraries/libbase/testcases/org/pentaho/reporting/libraries/base/config/DefaultConfigurationTest.java
- improve DefaultConfiguration.findPropertyKeys()
- Set is useless as Hashtable.keys() cannot return duplicate values
- replace TreeSet with array
- add tests
- avoid redundant Class.forName() calls in DefaultObjectFactory.get()
- introduce ObjectUtilities.instantiateSafe()
- update tests
- use System.arrayCopy() in AbstractAlignmentProcessor.shiftArray()
@tmorgner, review it please when you have time. 
Nothing serious here, just sent all my catches
=> [BACKLOG-5456] - Small improvements for PRD

engine/extensions-scripting/ivy.xml, engine/extensions-scripting/source/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/ScriptableDataFactory.java, engine/extensions-scripting/source/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/ScriptableDataFactoryModule.java, engine/extensions-scripting/source/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/parser/ScriptableDataSourceReadHandler.java, engine/extensions-scripting/source/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/writer/ScriptableDataFactoryBundleWriteHandler.java, engine/extensions-scripting/source/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/writer/ScriptableDataFactoryWriteHandler.java, engine/extensions-scripting/source/org/pentaho/reporting/engine/classic/extensions/modules/rhino/RhinoModule.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/ScriptableDataFactoryModuleIT.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/ScriptableDataFactoryTest.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/module.properties, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/parser/ConfigReadHandlerTest.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/parser/ScriptableDataSourceReadHandlerTest.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/parser/ScriptableDataSourceXmlFactoryModuleTest.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/writer/ScriptableDataFactoryBundleWriteHandlerTest.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/scriptable/writer/ScriptableDataFactoryWriteHandlerTest.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/modules/rhino/RhinoModuleIT.java, engine/extensions-scripting/test-src/org/pentaho/reporting/engine/classic/extensions/modules/rhino/module.properties
1. Fixed checkstyle issues.
2. Increased coverage, as a result now:
Unit tests coverage = 72.2%
Integration tests coverage = 6.6%
Overall coverage = 78.8%
3. Added hamcrest and mockito dependencies for testing purposes.
The extensions-scripting has org.pentaho.reporting.engine.classic.extensions.modules.rhino.RhinoExpression.java marked as deprecated. If we remove it we will increase overall coverage to 89.3%
@tmorgner @dkincade please review or find someone who can review this.
=> [TEST] Increase unit test coverage for engine/extensions-scripting

libraries/libpensol/ivy.xml, libraries/libpensol/source/org/pentaho/reporting/libraries/pensol/PublishRestUtil.java, libraries/libpensol/test/org/pentaho/platform/web/http/api/resources/RepositoryPublishResourceRevealer.java, libraries/libpensol/test/org/pentaho/reporting/libraries/pensol/PublishRestUtilTestIT.java, libraries/libpensol/test/org/pentaho/reporting/libraries/pensol/resources/TestRepositoryPublishResource.java
- use new endpoint, allowing encoded names
- add integration tests
- add jersey-test-framework as test dependency
@tmorgner, review it please.
This PR uses the endpoint which was introduced by https://github.com/pentaho/pentaho-platform/pull/2655
I added ```jersey-test-framework``` as test dependency (copied from ```platform```).
=> [BISERVER-11565] - File upload names fail if the name has double quotes

engine/core/build.properties
"test-src" is default source folder for integration tests also.
Now integration tests metrics work.
@tmorgner @lucboudreau please review
=> [BACKLOG-5384] Fixed source path for integration tests

build-res/multibuild-shared.xml
Removing subfloor prefix from the targets as the direct children are also multibuild and won't have it, adding jacoco-integration
=> [CLEANUP] - Multibuild target fix

libraries/libformula/source/org/pentaho/reporting/libraries/formula/function/userdefined/CsvArrayFunction.java, libraries/libformula/test/org/pentaho/reporting/libraries/formula/function/userdefined/CsvArrayFunctionTest.java
- backport 7d940d16914a692378884bb6841241c2943d3d2f
@tmorgner, review it please. This is a backport of https://github.com/pentaho/pentaho-reporting/pull/687
Also, please look at my comment there. You test passes always -- no matter was the fix applied or not
=> [SP-2218] - Backport of PRD-5561 - Libformula Copy/Paste bug in CsvArrayFunction (6.0 Suite)

libraries/libformula/source/org/pentaho/reporting/libraries/formula/function/userdefined/CsvArrayFunction.java, libraries/libformula/test/org/pentaho/reporting/libraries/formula/function/userdefined/CsvArrayFunctionTest.java
- backport 7d940d16914a692378884bb6841241c2943d3d2f and 3b7cc7ddf68bff66a1a215c7ed3b8ea80d67a633
- apply Pentaho Checkstyle rules to CsvArrayFunction
@tmorgner, review it please. This is backport of https://github.com/pentaho/pentaho-reporting/pull/687 and https://github.com/pentaho/pentaho-reporting/pull/697
=> [SP-2219] - Backport of PRD-5561 - Libformula Copy/Paste bug in CsvArrayFunction (5.4 Suite)

engine/core/test-src/org/pentaho/reporting/engine/classic/core/imagemap/parser/ImageMapWriterTest.java
Fix for http://devci.pentaho.com/job/master-snapshot/job/reporting-libraries/13/changes
@tmorgner Could you review this fix?
=> [BACKLOG-5384] Fixed using line separator for ImageMapWriterTest

engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/TextAreaParameterComponentTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/TextFieldParameterComponentTest.java
The reason of failing was junit assertions were before setting right values. The TextComponentEditHandler uses SwingUtilities.invokeLater method. I also used the same method for assertions. Another way would be using Thread.sleep... but I prefer SwingUtilities.invokeLater.
@tmorgner could you review?
=> [BACKLOG-5384] Fixed failed unit tests

libraries/libpensol/ivy.xml
Missing commons-logging library.
Was coming in transitively but now is not.
=> [CLEANUP] Fix build error

designer/report-designer-extension-pentaho/test-src/org/pentaho/reporting/designer/extensions/pentaho/repository/util/PublishSettingsTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/CrosstabHeaderTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/CrosstabOtherGroupBodyTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/CrosstabOtherGroupTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/CrosstabSummaryHeaderTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/CrosstabTitleHeaderTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/DetailsFooterTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/DetailsHeaderTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/GroupDataBodyTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/PageFooterTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/PageHeaderTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/RelationalGroupTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/StaticDataRowTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/WatermarkTest.java, engine/extensions/test-src/org/pentaho/reporting/engine/classic/extensions/modules/sbarcodes/elementfactory/BarcodeElementFactoryTest.java, engine/extensions/test-src/org/pentaho/reporting/engine/classic/extensions/modules/sparklines/elementfactory/BarSparklineElementFactoryTest.java, engine/extensions/test-src/org/pentaho/reporting/engine/classic/extensions/modules/sparklines/elementfactory/LineSparklineElementFactoryTest.java, engine/extensions/test-src/org/pentaho/reporting/engine/classic/extensions/modules/sparklines/elementfactory/PieSparklineElementFactoryTest.java
We cannot assume the system is stable until the reporting engine has been properly initialized. Manually registering parts of the system will not yield correct results, it needs a full boot. PublishSettingsTest cannot work as it uses the system-state dependent preferences API.
=> [CLEANUP] - Fix invalid tests. 

designer/report-designer/src/org/pentaho/reporting/designer/core/actions/global/OpenReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/actions/report/AbstractSaveReportAction.java, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/ReportRenderContext.java
Avoid to change last file name for report in case report attempted to be save with incorrect path.
We can't determine using file.getCanonicalPath() is path is correct since file can be saved in filesystem as far as in any independent destination and only call to SaveReportUtilities.saveReport(...) will give the real picture can't this file for any reason or been saved successful.
Refactoring to use 'ReportDesignerBoot.LAST_FILENAME' in all places where 'report-save-path' string was directly hard-coded.
=> PRD-5567 Tab of report displays not correctly information about stateof report.

engine/extensions-kettle/source/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/FormulaParameter.java, engine/extensions-kettle/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/kettle/FormulaParameterTest.java, libraries/libformula/source/org/pentaho/reporting/libraries/formula/util/FormulaUtil.java, libraries/libformula/test-src/org/pentaho/reporting/libraries/formula/util/FormulaUtilTest.java
The root cause of formulas not being saved is incorrect conversion of formulas parameters. Formulas since that never have been saved to report correctly. This issue being hided by arguments - so when arguments is existed for kettle query even formulas was not recognized - report been saved
correctly. If there was no arguments - formulas for kettle query were existed only in master report and never being saved to xml/zip file.
To fix that libformula/FormulaUtil.collectReferences(...) should start recognize LValue as FormulaFunction. So that we can be able to extract parameter references from formula, then - since we recognize references we will be able to create FormulaParameter in FormulaParameter.convert(
ParameterMapping[] ...) and since formulas being converted they will be processed …
=> PRD-5511 - PRD: Not saved parameter mapping when it uses formulas

engine/core/source/org/pentaho/reporting/engine/classic/core/layout/output/AbstractReportProcessor.java
Separately catch and re-throw ReportInterruptedException. Log stacktrace for debug level only. Interruption is not a error drama.
see https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/245
=> [BACKLOG-6988] - log if debug only if interrupted exception thrown.

designer/report-designer-extension-pentaho/source/org/pentaho/reporting/designer/extensions/pentaho/drilldown/swing/SwingRemoteDrillDownController.java
- Fix for the bug with pentaho-sugar-drilldown dialog that appeared in the latest QAT build.
=> [PRD-4160] Xul based DrillDown dialogs in Report Designer cannot be internationalized

engine/core/ivy.xml
Replace antrl-2.7.7 with antlr-3.4-complete which contains antlr-2.7.7
=> [BACKLOG-8389] - Upgrade antlr to version 3.4 across Pentaho product suite - changes for pentaho reporting repository

.gitignore, engine/tools/source/generators/ExpressionDeprecationValidator.java
Clean-up in non-production code. Removes need for apache-bcel library, which is no longer pulled in via ivy-resolve and was not needed anyway since JDK 1.6.
Also globally ignored checkstyle, as files needed for that check are pulled in by subfloor and therefore should not be under version control.
=> [CLEANUP] - engine/tools missing dependency, checkstyle directory ignored

engine/core/ivy.xml
Replace antrl-3.4-complete with antlr-complete-3.5.2 which contains antlr-2.7.7
=> [BACKLOG-8389] - Upgrade antlr to version 3.5.2 across Pentaho product suite - changes for pentaho reporting repository

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/rtf/RTFExportTask.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/xls/ExcelExportTask.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/gui/xls/XSSFExcelExportTask.java
Ensure that the export tasks provide an ERROR status on failure, instead of WARNING
=> [PDI-7502] Reporting Output Error on Failure

libraries/libpensol/ivy.xml
The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded: The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …
=> [BACKLOG-8388] Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelCellStyleBuilder.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/HSSFCellStyleProducer.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelCellStyleBuilderTest.java
Refactor HSSFCellStyleProducer using builder to be more testable.
In advance it would be better to have HSSFCellStyleKey and CellStyle crated in one place.
BACKLOG-10473 initially was introduced by addition of rotation property we came keys not matching according styles. Now should be corrected.
=> [BACKLOG-10473] - fix styles for 1+ excel sheets.

libraries/libxml/source/org/pentaho/reporting/libraries/xmlns/common/AttributeMap.java, libraries/libxml/test-src/org/pentaho/reporting/libraries/xmlns/common/AttributeMapTest.java
- check the value for null, and remove the entry from the attribute-map
=> [PRD-5785]-Morphing Resource Labels clearing out SubReport

designer/report-designer/src/org/pentaho/reporting/designer/core/splash/SplashScreen.java
- with the change in the splash screen image from having a white background to a dark blue one, the color of the text needs to be set to white ( in opposed to default black )
=> [BACKLOG-11620] Update product App icons and splash screens

designer/report-designer-assembly/resource/resources/classic-engine.properties, engine/core/source/org/pentaho/reporting/engine/classic/core/classic-engine.properties, engine/extensions-xpath/ivy.xml, engine/extensions-xpath/source/org/pentaho/reporting/engine/classic/extensions/datasources/xpath/LegacyXPathTableModel.java, engine/extensions-xpath/test-src/org/pentaho/reporting/engine/classic/extensions/datasources/xpath/LegacyXPathTableModelTest.java
[PPP-3584] PRD - Security Vulnerability when using XML file as datasource
- disable default support DTD in pentaho report designer
- add property for enable/disable support DTD
@pamval
=> [PPP-3584] PRD - Security Vulnerability when using XML file as datasource

designer/report-designer/ivy.xml, designer/report-designer/src/org/pentaho/reporting/designer/core/editor/parameters/ParameterDialog.java, designer/report-designer/test-src/org/pentaho/reporting/designer/core/editor/parameters/ParameterDialogTest.java
The tricky part is that if label of data format fields is empty, but formula are used - no attribute is set for label or data format. So having approach to add '-formula' will not help since we don't have such attributes at all.
In parameter dialog, as far as in bundle writers like [here](https://github.com/pentaho/pentaho-reporting/blob/497ca68305ea5183d8af0972aae339512791aae4/engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/DataDefinitionFileWriter.java#L218) we will not save empty attributes.
So in case of label of formula fields are empty - we will just write formula value there. On UI if we found that label value is equal to formula value - we just set empty text field. When going to save - replace empty with formula value again.
=> [BACKLOG-11906] - fix formula computation for empty label and data format

designer/report-designer-assembly/ivy.xml
@CodeOnCoffee @rmansoor @mbatchelor @pentaho/rogueone Please review
Related PRs:
https://github.com/pentaho/pentaho-platform/pull/3207
https://github.com/pentaho/pentaho-reporting/pull/869
https://github.com/pentaho/pentaho-reportdesigner-ee/pull/53
https://github.com/pentaho/pentaho-kettle/pull/3087
=> [BACKLOG-11621] Removes JTDS driver dependency

libraries/libxml/source/org/pentaho/reporting/libraries/xmlns/common/AttributeMap.java, libraries/libxml/test-src/org/pentaho/reporting/libraries/xmlns/common/AttributeMapTest.java
- check the value for null, and remove the entry from the attribute-map
=> [SP-2939][PRD-5785]-Morphing Resource Labels clearing out SubReport

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtility.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtilityTest.java
=> [SP-2951] Backport of PRD-5746 - Border radius values are saved under an incorrect key (6.1 Suite)

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/rtf/itext/PatchRtfTable.java
That's why they teach us to use iterators, when removing elements from a collection...
What happens here - we remove an element from a list and decrement it's size.
The size is not stored in a variable and is retrieved each time.
As a result we have only every other row in the report.
Simple demo: https://gist.github.com/EgorZhuk/34950613e64424c2b75ed13bbe137183
=> [PRD-5878]-Remove element from a list, the right way

assemblies/mac/src/main/resources/resource/report-designer.sh, assemblies/mac/src/main/resources/resource/set-pentaho-env.sh, assemblies/winlinux/src/main/resources/resource/report-designer.sh, assemblies/winlinux/src/main/resources/resource/set-pentaho-env.sh
- the problem with launcher directory was fixed
=> [PRD-5631] If report-designer.sh is launched from any directory other than its own, karaf fails to start

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/layout/TextStyleReadHandler.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtility.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/layout/TextStyleReaderHandlerTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtilityTest.java
=> [PRD-5914]-Property for "Word-Break" Unable to be Saved as "False" in Standard Report

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/commonswing/ReportProgressDialog.java
previewing a parameterized report without a query
=> [PRD-3322]-On Linux environments, loading dialog doesn't go away when

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/PentahoPathModel.java, designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/swing/SwingRemoteDrillDownController.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/DrillDownFunctionParameterEditor.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/basic/DefaultXulDrillDownController.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/model/DrillDownModel.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/swing/SwingGenericUrlDrillDownUi.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/drilldown/swing/SwingSelfDrillDownUi.java
- removed unnecessary parameters filtration;
- added a check before event creation;
- fixed formula creation - created formula now is valid by default;
- fixed unreported bug with '=' duplication on location changing;
=> [PRD-3954] DRILLDOWN Formula Editor, the Location resets unexpectedly

designer/datasource-editor-jdbc/pom.xml, designer/datasource-editor-mondrian/pom.xml, designer/datasource-editor-olap4j/pom.xml, designer/datasource-editor-pmd/pom.xml, designer/report-designer-extension-connectioneditor/pom.xml, designer/report-designer-extension-legacy-charts/pom.xml, designer/report-designer-extension-pentaho/pom.xml, designer/report-designer-extension-toc/pom.xml, designer/report-designer-extension-wizard/pom.xml, engine/demo/pom.xml, engine/extensions-mondrian/pom.xml, engine/extensions-reportdesigner-parser/pom.xml, engine/testcases/pom.xml, engine/tools/pom.xml
- removed explicit xerces dependencies. test usages of xerces are only left
=> [PPP-3566] Use of vulnerable component xerces:xercesImpl:2.9.1and 2.11.0 - CVE-2009-2625 and CVE-2013-4002

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/layout/TextStyleReadHandler.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtility.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/layout/TextStyleReaderHandlerTest.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtilityTest.java
=> [SP-3724][PRD-5914]-Property for "Word-Break" Unable to be Saved as "False" in Standard Report

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/settings/ProxySettings.java
@pentaho/rebelalliance @pentaho/rogueone @tmorgner 
Please review.
This fixed 'UnknownHostException: localhost' exception thrown from the new driver.
=> [BACKLOG-17345] Reset system properties to null instead of empty string to avoid UnknownHostException with new Postgres driver

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/preview/ReportPreviewComponent.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/commonswing/ReportProgressDialog.java
previewing a parameterized report without a query
=> [SP-3728]-On Linux environments, loading dialog doesn't go away when

engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/layout/TextStyleReadHandler.java, engine/core/source/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtility.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/layout/TextStyleReaderHandlerTest.java, engine/core/test-src/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/StyleWriterUtilityTest.java
=> [SP-3725][PRD-5914]-Property for "Word-Break" Unable to be Saved as "False" in Standard Report

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/settings/ProxySettings.java
@tmorgner @pentaho/rogueone @pentaho/rebelalliance 
Please review.
System.setProperty() doesn't allow null value, instead of setting them to be empty string or null, System.clearProperty() should be called for reset.
=> [BACKLOG-18985] Fixed NPE, instead of resetting system properties to empty or null, they should be cleared.

assemblies/pom.xml, designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/PentahoParameterRefreshHandler.java, designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/repository/actions/UpdateReservedCharsTask.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/util/HttpClientManager.java, engine/extensions-cda/src/main/java/org/pentaho/reporting/engine/classic/extensions/datasources/cda/HttpQueryBackend.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/PentahoSolutionFileProvider.java, libraries/libpensol/src/main/java/org/pentaho/reporting/libraries/pensol/vfs/LocalFileModel.java, pom.xml
Removed org.apache.karaf.jaas.modules-x.x.x.jar http://jira.pentaho.com/browse/BACKLOG-18473 
Contained old version of http-client inside.
=> [BACKLOG-19148]-java.lang.UnsupportedOperationException error in Pentaho Report Designer when publishing report to the server

designer/datasource-editor-pmd/pom.xml, pom.xml
@pentaho/2-1b 
Depends on https://github.com/pentaho/mql-editor/pull/47
=> [BACKLOG-20450] Downstream update for mql-editor

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/ReportRenderContext.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/Prd2943Test.java
- only master report own a valuable changeTracker field - all subreports use the master report's one.
- tests were added
=> [PRD-2943] Hitting save on subreport tab does not reset the change flag for the other subreports and master reports.

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/parser/base/common/ExpressionReadHandler.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/parser/bundle/writer/ExpressionWriterUtility.java, libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/text/URLBuilderFunction.java, libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/text/URLBuilderFunctionDescription.java, libraries/libformula/src/main/resources/org/pentaho/reporting/libraries/formula/function/text/URLBuilder-Function.properties, libraries/libformula/src/main/resources/org/pentaho/reporting/libraries/formula/libformula.properties
Fix for the missed function URLBUILDER which is used in drilldown.properties
Some default samples uses drilldown.
Fix for serialization into prpt failonerror property (before it was ignored).
=> [PRD-4595]-Errors from the datasource used in a SINGLEVALUEQUERY function are consumed silently

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/DatePickerParameterComponent.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/gui/base/parameters/DatePickerParameterComponentTest.java
* Always set the timezone and disable the lenient parsing flag when a date format is created.
=> [PRD-5956] - PRD parameter viewer not handling timezones correctly

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/ReportRenderContext.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/Prd2943Test.java
=> [SP-4172] Backport of PRD-2943 - Hitting save on subreport tab does not reset the change flag for the other subreports and master reports. (8.0 Suite)

designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/editor/ReportRenderContext.java, designer/report-designer/src/test/java/org/pentaho/reporting/designer/Prd2943Test.java
=> [SP-4171] Backport of PRD-2943 - Hitting save on subreport tab does not reset the change flag for the other subreports and master reports. (7.1 Suite)

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/swing/SwingRemoteDrillDownController.java
@tmorgner 
The var designerContext from AbstractStringValueCellEditor.java wasn't being initiated.
Before refactoring the code under PRD-4160, this var was being initiated by DefaultXulDrillDownController (l.164) calling function setReportDesignContext.
=> [PRD-5987] 7.1 & 8.0: Drop Down Arrow Missing for Parameter Values in Hyperlink to Pentaho Repository prpt

assemblies/pom.xml
@emartin-pentaho @lgrill-pentaho @kcruzada @mbatchelor
=> [BACKLOG-23036] stop excluding mapreduce libs zip from assembly

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/parameters/Messages.java, libraries/libbase/pom.xml, libraries/libbase/src/main/java/org/pentaho/reporting/libraries/base/util/ResourceBundleSupport.java
* Fixed the retrieval of L10N info.
@pentaho-lmartins , @graimundo , @mbatchelor , @pamval Please review and merge if it's all ok.
Note: I didn't add the usual unit test in this commit, because the change was regarding the retrieve of a value between different repos (i.e. pentaho-reporting and pentaho-platform-core), but also because the testable result is highly dependent on the specific system configured locale.
=> [PIR-1172] - L10N - Untranslated string in PIR prompt.

libraries/libformula-ui/src/main/java/org/pentaho/openformula/ui/model2/FormulaParser.java, libraries/libformula-ui/src/test/java/org/pentaho/openformula/ui/FormulaDocumentTest.java
The open parenthesis characters were being normalized as FormulaFunctionElement's and not as FormulaOpenParenthesisElement's - bugging all the open and close parenthesis logic. 
This PR adds that clause, ensuring that.
@tmorgner
=> [PRD-5009] Formula editor does not handle complex terms properly

designer/report-designer-extension-pentaho/src/main/java/org/pentaho/reporting/designer/extensions/pentaho/drilldown/PentahoParameterRefreshHandler.java
1.  With the work done for BISERVER-13648, the server no longer return an auth challenge to the issued request ( when this used to be the case, the HttpClient lib would handle such a 401 response OOTB by issuing the credentials should any have been set in the HTTPContext ).
2. Now ( i.e. post BISERVER-13648 ), the server returns a 302 REDIRECT to the server's /Login page.
3. We can circumvent by defining an  HttpClientContext with preemptive authentication set.
4. Note that we're only setting preemptive auth for this request and no others, given that this is the only request that goes through the server's `/api/repos/**` spring-security regex. Other requests are working as intended, but are issued towards other regexs, for which BISERVER-13648 did not change their behaviour
@pamval …
=> [BACKLOG-26393] Report Designer hyperlinking not working

engine/extensions-kettle/pom.xml, pom.xml
Remove unused dependency for janino library. Testing in pdi-ce (pentaho-kettle), and pdr-ce (pentaho-reporting). See 
https://jira.pentaho.com/browse/BACKLOG-27258 for details.
=> [BACKLOG-27258] UDJCs work inconsistently across different OS in 8.2

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/csv/CsvTemplateProducer.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/csv/CsvTemplateProducerTest.java
* [PRD-5412] Added in a line for printing the separator when there's a spanned cell (empty cell). This ensures that the empty cell gets represented and we move on to the next column/row pair.
* [PRD-5412] Updating copyright year
* [PRD-5412] Adding Test file to verify producing a template.
=> [PRD-5412] CSV Output changes the alignment of header row and adds a trailing separator to the report

assemblies/prd-ce/pom.xml, pom.xml
When replacing felix framework implementation for OSGi core specification 4.3.1 which is the spec we aim at (see pentaho-parent-pom ) in our Karaf 3.0.3 assembly an error occurs:
```
ERROR: Bundle org.ops4j.pax.url.mvn [1] Error starting mvn:org.ops4j.pax.url/pax-url-aether/2.3.0
(java.lang.NoSuchMethodError: >org.osgi.framework.wiring.BundleWire.getProvider()
```
In this assembly we are using Felix Framework 4.2.1, which is partially OSGi 5.0 complaint. In particular, it is complaint with the org.osgi.framework.wiring.BundleWire.getProvider() method.
For this reason we are explicitly overriding OSGi core to 5.0.0 here.
@nantunes please review
=> [BACKLOG-27573] - Replaced Felix framework 4.4.1 with OSGi core 5.0.0.

assemblies/prd-ce/pom.xml
Merge after https://github.com/pentaho/maven-parent-poms/pull/105.
@graimundo please review.
=> [BACKLOG-27567] Remove org.osgi.core version override

engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/ReportEnvironmentDataRowTest.java
@pentaho/millenniumfalcon please review.
=> [CLEANUP] Make ReportEnvironmentDataRowTest independent of the system locale

libraries/libloader/pom.xml, libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/ResourceKey.java, libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/loader/fileobject/FileObjectResourceData.java, libraries/libloader/src/main/java/org/pentaho/reporting/libraries/resourceloader/loader/fileobject/FileObjectResourceLoader.java, libraries/libloader/src/main/resources/org/pentaho/reporting/libraries/resourceloader/loader.properties, libraries/libloader/src/test/java/org/pentaho/reporting/libraries/resourceloader/ResourceKeyTest.java, libraries/libloader/src/test/java/org/pentaho/reporting/libraries/resourceloader/loader/fileobject/FileObjectResourceLoaderTest.java
1. Added new implementation of `ResourceData` and `ResourceLoader` for Apache VFS's `FileObject`.
2. Added this new `FileObjectResourceLoader` to `loader.properties`
@tmorgner @pentaho/rogueone 
Note: To be merged with: https://github.com/pentaho/pentaho-kettle/pull/6372
=> [PDI-15742] Unable to load a prpt from the repository in the Pentaho Reporting Output step

pom.xml
Removal of the Apache Derby version in favor of retrieving a unified version from the Maven parent POM. At the time of this PR, the latest version of Apache Derby is 10.15.1.3. Other PRs related to this one are listed below:
https://github.com/pentaho/maven-parent-poms/pull/122
https://github.com/pentaho/pentaho-platform/pull/4399
https://github.com/pentaho/pentaho-kettle/pull/6402
https://github.com/pentaho/pentaho-reporting/pull/1256
https://github.com/pentaho/data-access/pull/1053
=> [BACKLOG-28357] Updates derby version, retrieves from parent POM

pom.xml
aws-java-sdk-core depends on a later version, so bringing this to the latest
=> [BACKLOG-27345] - upgrading joda time

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/datetime/TodayFunction.java, libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/datetime/YesterdayFunction.java, libraries/libformula/src/test/java/org/pentaho/reporting/libraries/formula/function/datetime/NowFunctionTest.java, libraries/libformula/src/test/java/org/pentaho/reporting/libraries/formula/function/datetime/TodayFunctionTest.java, libraries/libformula/src/test/java/org/pentaho/reporting/libraries/formula/function/datetime/YesterdayFunctionTest.java
Reverts pentaho/pentaho-reporting#1282
@pentaho-lmartins 
PR to revert this issue, since it already breaks tests in cda and also according to Thomas Morgner, this can only bring other kinds of errors
=> Revert "[PRD-6070] Date Picker showing incorrect value when client is in diff…"

designer/datasource-editor-jdbc/pom.xml, engine/extensions-kettle/pom.xml, libraries/libloader/pom.xml, pom.xml
This reverts commit 80a4bab4d57dfd5f06855b7a6e5fcffc372d92ca, reversing
changes made to dce179b93206b927263ce6735c19df4fb00e07bf.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
=> Revert "Merge pull request #1328 from gryphendowre/SP-5370"

assemblies/prd-ce/pom.xml, assemblies/prd-ce/src/main/resources/resource/resources/log4j2.xml, assemblies/sample-war/pom.xml, assemblies/samples/pom.xml, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/actions/global/QuitAction.java, engine/demo/pom.xml, engine/extensions-kettle/pom.xml, pom.xml
* [BISERVER-14721] Upgrade to log4j2.
* [BISERVER-14721] Upgrade to log4j2
* [BISERVER-14720] Removes unused kettle-log4j-core.
* [BISERVER-14720] Fix path in log4j2.xml
Co-authored-by: Luc Boudreau <lucboudreau@gmail.com>
=> [SP-6107] Upgrades log4j2

assemblies/prd-ce/pom.xml, assemblies/prd-ce/src/main/resources/resource/resources/log4j2.xml, assemblies/sample-war/pom.xml, assemblies/samples/pom.xml, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/actions/global/QuitAction.java, engine/demo/pom.xml, engine/extensions-kettle/pom.xml, pom.xml
* [BISERVER-14721] Upgrade to log4j2.
* [BISERVER-14721] Upgrade to log4j2
* [BISERVER-14720] Removes unused kettle-log4j-core.
* [BISERVER-14720] Fix path in log4j2.xml
Co-authored-by: Luc Boudreau <lucboudreau@gmail.com>
=> [SP-6106] Upgrades log4j2

libraries/libswing/src/main/java/org/pentaho/reporting/libraries/designtime/swing/MacOSXIntegration.java
Removing use of com.apple.eawt.ApplicationListener which is no longer available in Java on MacOS
=> [BACKLOG-35738] Fix for exception on startup on MacOS

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/AbstractHtmlPrinter.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/GlobalStyleManager.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/html/helper/StyleBuilder.java
This PR adds a new style to the global style manager necessary for sticky headers, whether or not anything actually uses that style. By default, it will not be used.
This style will not be added if reporting is set to use inline styles.
=> [BACKLOG-37746] Add option to freeze top row in HTML reports

libraries/libformula/src/main/java/org/pentaho/reporting/libraries/formula/function/math/Atan2Function.java, libraries/libformula/src/test/java/org/pentaho/reporting/libraries/formula/function/math/ATAN2FunctionTest.java
Two Issues with the code: 
(1) incorrect index used for 2nd parameter
(2) Order of passing parameter is incorrect in Math.atan2(double y, double x)
**Testing results**
=> [PDI-19695] - Formula ATAN2 is not working as expected

engine/extensions-kettle/pom.xml, pom.xml
any of this code.  Removing to simplify dependency management.
=> [PPP-4848] commons-net has a security vulnerability, but is not used by

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/output/AbstractOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/output/OutputProcessorFeature.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/FlowExcelOutputProcessor.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelOutputProcessorMetaData.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinter.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/helper/ExcelPrinterBase.java, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/config-description.xml, engine/core/src/main/resources/org/pentaho/reporting/engine/classic/core/modules/output/table/xls/configuration.properties
Adding support for new Excel export settings.
See: https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/1045
=> [BISERVER-14865] - Impossible to download PIR reports onto Excel 2007 format once data is past Excel limitations

engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/layout/HtmlRichTextProcessingTest.java
PR containing only the unit test related to PRD-6160 for QA purposes. The fix will be introduced in a following PR.
@pentaho/tatooine_dev
=> [PRD-6160] - When rendering html richtext containing style and fontsize specified in "px" then this text is displayed too big

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/layout/richtext/HtmlRichTextConverter.java
Fix for PRD-6160. This PR should only be merged after the [PR](https://github.com/pentaho/pentaho-reporting/pull/1662) with the corresponding unit test is merged, for QA purposes.
@pentaho/tatooine_dev
=> [PRD-6160] - When rendering html richtext containing style and fontsize specified in "px" then this text is displayed too big (fix)

designer/report-designer/pom.xml, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/model/data/AsynchronousDataSchemaManager.java, pom.xml
relates to [PPP-4541] Use of Vulnerable Component: Components/scala
- Updated akka-actor to nearest, non-vulnerable version
- This new version has an updated scala library version that depricated `onSuccess` and `onFailure`
[PPP-4541]: https://hv-eng.atlassian.net/browse/PPP-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4537][PPP-4541] Use of Vulnerable Component: Components/akka, scala

pom.xml
- Update groovy minor version to 2.4.21 to address CVE-2020-17521
JIRA: https://hv-eng.atlassian.net/browse/PPP-4784
PR Set:
- https://github.com/pentaho/pentaho-platform/pull/5680
- https://github.com/pentaho/pentaho-reporting/pull/1676
- https://github.com/pentaho/big-data-plugin/pull/2584
- https://github.com/pentaho/pentaho-big-data-ee/pull/612
- https://github.com/pentaho/mondrian/pull/1386
=> [PPP-4784] Vulnerable Component: groovy

designer/report-designer/pom.xml, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/model/data/ActorSystemHost.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/model/data/AsynchronousDataSchemaManager.java, designer/report-designer/src/main/java/org/pentaho/reporting/designer/core/model/data/QueryMetaDataActorImpl.java, pom.xml
relates to [PPP-4541] Use of Vulnerable Component: Components/scala
SECOND PR TO ADDRESS LICENSING ISSUE
See https://hv-eng.atlassian.net/browse/PPP-4537?focusedCommentId=2056460
- Changed akka version to nearest version with acceptable licensing model (Apache)
- Excluded transitive scala dependencies from akka
- Explicitly pulled in non-vulnerable scala version dependency
See previous commit 5c7a844e811f9dac7830aecf0fe10925055cdbb5
[PPP-4541]: https://hv-eng.atlassian.net/browse/PPP-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4537] Use of Vulnerable Component: Components/akka

pom.xml
Jira: https://hv-eng.atlassian.net/browse/PPP-4899
- Update xmlgraphics-commons 2.2 -> 2.9 -- this gets us to commons-io 2.16.1, which is 2.7+, addressing CVE-2021-29425
```
[INFO] org.pentaho.reporting.library:libloader:jar:10.3.0.0-SNAPSHOT
...
[INFO] +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.9:compile
[INFO] |  \- commons-io:commons-io:jar:2.16.1:compile
```
Related PRs:
https://github.com/pentaho/pentaho-kettle/pull/9525
https://github.com/pentaho/maven-parent-poms/pull/588
=> [PPP-4899] Vulnerable Component: commons-io

pom.xml
[SP-6602]-Backport of PPP-4968 - Vulnerable Component: xmlbeans 2.5.0 (10.2 Suite)
[SP-6602]: https://hv-eng.atlassian.net/browse/SP-6602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SP-6602]-Backport of PPP-4968 - Vulnerable Component: xmlbeans 2.5.0 (10.2 Suite)

engine/core/pom.xml, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/event/async/AsyncExecutionStatus.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/event/async/AsyncReportState.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/event/async/AsyncReportStatusListener.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/event/async/IAsyncReportListener.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/event/async/IAsyncReportState.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/event/async/IReportCancelEvent.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/event/async/ReportListenerThreadHolder.java, engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/modules/misc/datafactory/sql/SimpleSQLReportDataFactory.java
https://pentaho-jira-archive.orl.eng.hitachivantara.com/browse/BISERVER-10627 This jira introduced cancellation of the report on user's request. All of this code due to some reasons was put in reporting plugin instead of reporting-core. I have move some there classes to engine-core.
The classes and interfaces were move from https://github.com/pentaho/pentaho-platform-plugin-reporting project by this PR https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/855
=> [PIR-1513] - Moving some of the core classes and interface for async report generation to the reporting core library

engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/layout/HtmlRichTextProcessingTest.java
PR containing only the unit test related to PRD-6160 for QA purposes. The fix will be introduced in a following PR.
original PR: https://github.com/pentaho/pentaho-reporting/pull/1662
@pentaho/tatooine_dev
=> Backport of PRD-6160 - When rendering html richtext containing style and fontsize specified in "px" then this text is displayed too big (10.2 Suite)

engine/core/pom.xml, libraries/libpensol/pom.xml, pom.xml
cherry-pick of [d4620d](https://github.com/pentaho/pentaho-reporting/commit/d4620d953b4c177a34591833ab7fe8a393f8e950) from PR: https://github.com/pentaho/pentaho-reporting/pull/1738
=> [SP-6771] Backport of MONDRIAN-2749 - CellFormatter scripting capability broken due to removal of Nashorn scripting engine from JDK (10.2 Suite)

engine/core/src/main/java/org/pentaho/reporting/engine/classic/core/metadata/ElementTypeRegistry.java, engine/core/src/test/java/org/pentaho/reporting/engine/classic/core/modules/output/fast/ReportStructureValidatorTest.java
This fixes an issue that was making the UT `AttributeMetaDataValidationTest.testMetaData` fail on local maven runs of `engine.core` module. 
The issue was caused by adding the `BarcodeDummyType` to the `ElementTypeRegistry` instance. Since the validations in `AttributeMetaDataValidationTest.testMetaData` would then fail for this particular type.
The fix adds a cleanup step in the unit test that removes the `BarcodeDummyType`, from the registry, in the end of the test execution.
Failure stack trace:
```
[INFO] Running org.pentaho.reporting.engine.classic.core.metadata.AttributeMetaDataValidationTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.371 s <<< FAILURE! - in org.pentaho.reporting.engine.classic.core.metadata.AttributeMetaDataValidationTest
[ERROR] …
```
=> chore: cleanup for testBarcodeDetection unit test
